"""BACK-STRONG — Claude-authored module.

Source: new_modules.md. Flagged is_authored_extension=True.
"""
from models.module import (
    Emotion,
    FailedSolution,
    RootCause,
    NutritionTarget,
    Food,
    ExerciseRecommended,
    ExerciseAvoid,
    WorkoutExercise,
    WorkoutRoutine,
    ModuleConstraint,
    Habit,
    PsychologyThought,
    PlateauAction,
    FAQ,
    TrackerColumn,
    Module,
)


MODULE = Module(
    slug="back_strong",
    display_name="Back-Strong",
    audience="Adults aged 25-55 with chronic lower back pain, often from desk jobs",
    primary_goal="Fat loss / muscle gain while strengthening (not aggravating) the back",
    pain_level=7,
    urgency=7,
    main_barrier="Standard programs include deadlifts/heavy bending; fear of re-injury; desk-job posture",
    is_authored_extension=True,
    content_pending=False,
    emotions=[
        Emotion(emotion="Fear", exact_phrase="I'm scared one wrong move will set me back.", sort_order=1),
        Emotion(emotion="Frustration", exact_phrase="I can't sit through a workday without pain.", sort_order=2),
        Emotion(emotion="Discouragement", exact_phrase="I used to be active; now I'm afraid to move.", sort_order=3),
        Emotion(emotion="Anxiety", exact_phrase="Will this ever fully heal?", sort_order=4),
        Emotion(emotion="Helplessness", exact_phrase="Every program assumes a healthy back.", sort_order=5),
        Emotion(emotion="Guilt", exact_phrase="I avoid exercise because I'm scared of the pain.", sort_order=6),
    ],
    failed_solutions=[
        FailedSolution(solution_tried="Generic strength programs", why_it_failed="Include deadlifts/heavy spinal loading too early", sort_order=1),
        FailedSolution(solution_tried="Complete bed rest / inactivity", why_it_failed="Weakens core and back muscles further; pain often worsens", sort_order=2),
        FailedSolution(solution_tried="Random core exercises", why_it_failed="Some (e.g., full sit-ups) increase spinal compression", sort_order=3),
        FailedSolution(solution_tried="Pain medication as the only strategy", why_it_failed="Masks symptoms without addressing the underlying weakness", sort_order=4),
        FailedSolution(solution_tried="Inconsistent stretching only", why_it_failed="No strength component; doesn't build lasting support", sort_order=5),
    ],
    root_causes=[
        RootCause(category="Biological", root_cause="Weak core and posterior chain (glutes, lower back)", sort_order=1),
        RootCause(category="Biological", root_cause="Poor spinal mobility/stiffness", sort_order=2),
        RootCause(category="Biological", root_cause="Prior injury or disc-related sensitivity", sort_order=3),
        RootCause(category="Lifestyle", root_cause="Prolonged sitting (desk job posture)", sort_order=4),
        RootCause(category="Lifestyle", root_cause="Poor lifting mechanics in daily life", sort_order=5),
        RootCause(category="Psychological", root_cause="Fear-avoidance (avoiding movement entirely, which weakens support muscles)", sort_order=6),
    ],
    nutrition_targets=[
        NutritionTarget(field_name="Protein Target", field_value="100-120g per day (supports muscle recovery and core strength)", sort_order=1),
        NutritionTarget(field_name="Anti-inflammatory Focus", field_value="Omega-3s, turmeric, ginger, colorful vegetables", sort_order=2),
        NutritionTarget(field_name="Weight Management", field_value="Excess weight increases spinal load; fat loss (if applicable) reduces mechanical stress", sort_order=3),
        NutritionTarget(field_name="Hydration", field_value="2.5-3 liters/day (disc and tissue health)", sort_order=4),
    ],
    foods=[
        Food(diet_type="vegetarian", food_type="Protein", options="Paneer, Greek yogurt, Tofu, Moong dal, Lentils, Chickpeas, Eggs", sort_order=1),
        Food(diet_type="vegetarian", food_type="Anti-inflammatory", options="Turmeric, Ginger, Walnuts, Flax seeds, Green tea", sort_order=2),
        Food(diet_type="vegetarian", food_type="Carbs", options="Quinoa, Brown rice, Sweet potato, Oats", sort_order=3),
        Food(diet_type="vegetarian", food_type="Vegetables", options="Spinach, Broccoli, Bell peppers, Berries", sort_order=4),
        Food(diet_type="non_vegetarian", food_type="Protein", options="Eggs, Chicken (lean), Fish (salmon, sardines)", sort_order=1),
        Food(diet_type="non_vegetarian", food_type="Anti-inflammatory", options="Salmon (omega-3), Sardines, Turmeric, Ginger", sort_order=2),
        Food(diet_type="non_vegetarian", food_type="Carbs", options="Quinoa, Brown rice, Sweet potato", sort_order=3),
        Food(diet_type="non_vegetarian", food_type="Vegetables", options="Spinach, Broccoli, Bell peppers, Berries", sort_order=4),
    ],
    exercises_recommended=[
        ExerciseRecommended(exercise_type="Walking", frequency="Daily", duration="20-30 min", benefits="Low-impact movement; promotes circulation without spinal load", sort_order=1),
        ExerciseRecommended(exercise_type="Core Stability Work (anti-extension/rotation)", frequency="4x/week", duration="15-20 min", benefits="Builds support around the spine without compressive bending", sort_order=2),
        ExerciseRecommended(exercise_type="Glute/Hip Strengthening", frequency="3x/week", duration="20 min", benefits="Reduces lower back compensation", sort_order=3),
        ExerciseRecommended(exercise_type="Swimming", frequency="1-2x/week", duration="30 min", benefits="Zero-impact, builds back strength safely", sort_order=4),
        ExerciseRecommended(exercise_type="Mobility (cat-cow, hip flexor stretch)", frequency="Daily", duration="10 min", benefits="Maintains spinal mobility, reduces stiffness", sort_order=5),
    ],
    exercises_avoid=[
        ExerciseAvoid(exercise_type="Heavy deadlifts/loaded bending (early stage)", why_avoid="High spinal compression risk before adequate core strength built", sort_order=1),
        ExerciseAvoid(exercise_type="Full sit-ups / weighted spinal flexion", why_avoid="Increases disc pressure", sort_order=2),
        ExerciseAvoid(exercise_type="High-impact running (on flare days)", why_avoid="Jarring load on the spine", sort_order=3),
        ExerciseAvoid(exercise_type="Twisting under load", why_avoid="Rotational stress on a sensitive spine", sort_order=4),
    ],
    workout_routines=[
        WorkoutRoutine(
            time_minutes=15,
            location="any",
            routine_label="15-Minute Back-Safe Routine",
            exercises=[
                WorkoutExercise(exercise_name="Warm-up Walk", reps_or_time="3 min", rest="—", sort_order=1),
                WorkoutExercise(exercise_name="Cat-Cow Stretch", reps_or_time="10 reps", rest="—", sort_order=2),
                WorkoutExercise(exercise_name="Bird Dogs", reps_or_time="10 reps each side", rest="15 sec", sort_order=3),
                WorkoutExercise(exercise_name="Glute Bridges", reps_or_time="12 reps", rest="10 sec", sort_order=4),
                WorkoutExercise(exercise_name="Dead Bug", reps_or_time="10 reps each side", rest="15 sec", sort_order=5),
                WorkoutExercise(exercise_name="Cool-down Stretch", reps_or_time="3 min", rest="—", sort_order=6),
            ],
            sort_order=1,
        ),
        WorkoutRoutine(
            time_minutes=30,
            location="any",
            routine_label="30-Minute Back-Safe Routine",
            exercises=[
                WorkoutExercise(exercise_name="Warm-up Walk", reps_or_time="5 min", rest="—", sort_order=1),
                WorkoutExercise(exercise_name="Bird Dogs", reps_or_time="12 reps each side", sets="3", rest="20 sec", sort_order=2),
                WorkoutExercise(exercise_name="Glute Bridges", reps_or_time="15 reps", sets="3", rest="20 sec", sort_order=3),
                WorkoutExercise(exercise_name="Dead Bug", reps_or_time="12 reps each side", sets="3", rest="20 sec", sort_order=4),
                WorkoutExercise(exercise_name="Standing Resistance Band Rows", reps_or_time="12 reps", sets="3", rest="30 sec", sort_order=5),
                WorkoutExercise(exercise_name="Wall Sit", reps_or_time="20 sec", sets="3", rest="20 sec", sort_order=6),
                WorkoutExercise(exercise_name="Cool-down Stretch", reps_or_time="5 min", rest="—", sort_order=7),
            ],
            sort_order=2,
        ),
    ],
    constraints=[
        ModuleConstraint(constraint_name="Back Pain (active flare)", solution="Gentle movement only", approach="Walking + cat-cow + gentle stretching", sort_order=1),
        ModuleConstraint(constraint_name="Home Workout", solution="Bodyweight core-stability options", approach="Bird dogs, Dead bugs, Glute bridges", sort_order=2),
        ModuleConstraint(constraint_name="Gym Workout", solution="Machine-supported, controlled range", approach="Seated rows, Lat pulldown, Leg press", sort_order=3),
        ModuleConstraint(constraint_name="Desk Job (prolonged sitting)", solution="Movement breaks", approach="Stand/stretch every 45-60 min; short walks", sort_order=4),
    ],
    habits=[
        Habit(habit_name="Pain Check-in", daily_target="Before/after each session", how_to_track="Rate pain 1-10 in journal", sort_order=1),
        Habit(habit_name="Posture Breaks", daily_target="Every 45-60 min", how_to_track="Phone reminder / app", sort_order=2),
        Habit(habit_name="Mobility Work", daily_target="10 min/day", how_to_track="Stretch journal / app", sort_order=3),
        Habit(habit_name="Protein Intake", daily_target="100-120g", how_to_track="Food tracker app", sort_order=4),
        Habit(habit_name="Water", daily_target="2.5-3 liters", how_to_track="Water bottle with marks", sort_order=5),
    ],
    psychology_thoughts=[
        PsychologyThought(common_thought="One wrong move will ruin everything.", emotional_impact="Fear", solution="Reframe: gradual core-building reduces re-injury risk over time", sort_order=1),
        PsychologyThought(common_thought="I used to be active; now I'm afraid.", emotional_impact="Grief/Discouragement", solution="Movement (not rest) is part of recovery once cleared for gentle exercise", sort_order=2),
        PsychologyThought(common_thought="Nothing is made for people like me.", emotional_impact="Isolation", solution="This plan is built specifically around the constraint, not despite it", sort_order=3),
        PsychologyThought(common_thought="I'll never be pain-free.", emotional_impact="Hopelessness", solution="Many people significantly reduce pain with consistent core/glute strengthening", sort_order=4),
    ],
    plateau_actions=[
        PlateauAction(trigger_condition="Pain not improving (2+ weeks)", action_to_take="Reduce range/intensity further; consult a physiotherapist", timeframe="Immediate", sort_order=1),
        PlateauAction(trigger_condition="Core strength plateau", action_to_take="Increase hold time before increasing reps", timeframe="Week 3-4", sort_order=2),
        PlateauAction(trigger_condition="No fat-loss results (4+ weeks)", action_to_take="Reassess calorie intake; back pain shouldn't block nutrition progress", timeframe="Week 4", sort_order=3),
    ],
    faqs=[
        FAQ(question="Can I still build muscle with back pain?", answer="Yes. Focus on core stability, glute strengthening, and pain-free ranges of motion.", sort_order=1),
        FAQ(question="Should I avoid all bending and lifting?", answer="No — but build core strength first, then reintroduce controlled loaded movement gradually.", sort_order=2),
        FAQ(question="When should I see a doctor instead of following this plan?", answer="If there's numbness, tingling down the leg, or worsening pain, see a doctor or physiotherapist before continuing.", sort_order=3),
        FAQ(question="Is walking safe for back pain?", answer="Generally yes — it's one of the most recommended movements for non-specific lower back pain.", sort_order=4),
    ],
    tracker_columns=[
        TrackerColumn(column_name="Weight", sort_order=1),
        TrackerColumn(column_name="Pain Level (1-10)", sort_order=2),
        TrackerColumn(column_name="Core Strength (1-10)", sort_order=3),
        TrackerColumn(column_name="Steps/Day", sort_order=4),
        TrackerColumn(column_name="Protein (g)", sort_order=5),
        TrackerColumn(column_name="Notes", sort_order=6),
    ],
)
