"""CALM STRENGTH — Claude-authored module.

Source: new_modules.md. Flagged is_authored_extension=True.
"""
from models.module import (
    Emotion,
    FailedSolution,
    RootCause,
    NutritionTarget,
    Food,
    ExerciseRecommended,
    ExerciseAvoid,
    WorkoutExercise,
    WorkoutRoutine,
    ModuleConstraint,
    Habit,
    PsychologyThought,
    PlateauAction,
    FAQ,
    TrackerColumn,
    Module,
)


MODULE = Module(
    slug="calm_strength",
    display_name="Calm Strength",
    audience="Adults aged 22-50 under sustained high stress, regardless of occupation",
    primary_goal="Fat loss / maintenance + nervous system recovery + energy stabilization",
    pain_level=8,
    urgency=8,
    main_barrier="More intense workouts make them feel worse, not better; can't out-train chronic stress",
    is_authored_extension=True,
    content_pending=False,
    emotions=[
        Emotion(emotion="Overwhelm", exact_phrase="I'm wired but exhausted.", sort_order=1),
        Emotion(emotion="Anxiety", exact_phrase="My mind never switches off.", sort_order=2),
        Emotion(emotion="Frustration", exact_phrase="I work out hard and still feel awful.", sort_order=3),
        Emotion(emotion="Guilt", exact_phrase="I don't have the energy to do what I 'should.'", sort_order=4),
        Emotion(emotion="Numbness", exact_phrase="I'm just running on autopilot.", sort_order=5),
        Emotion(emotion="Fear", exact_phrase="I'm scared this stress is doing long-term damage.", sort_order=6),
    ],
    failed_solutions=[
        FailedSolution(solution_tried="High-intensity workouts to 'burn off stress'", why_it_failed="Raises cortisol further; leaves them more depleted", sort_order=1),
        FailedSolution(solution_tried="Caffeine to push through fatigue", why_it_failed="Masks exhaustion; worsens sleep and anxiety", sort_order=2),
        FailedSolution(solution_tried="Ignoring stress and 'just training harder'", why_it_failed="Body interprets training as additional stress on top of life stress", sort_order=3),
        FailedSolution(solution_tried="Generic fitness programs", why_it_failed="No stress/recovery component; assume unlimited recovery capacity", sort_order=4),
        FailedSolution(solution_tried="All-or-nothing mentality", why_it_failed="Burns out after a few intense weeks; unsustainable", sort_order=5),
    ],
    root_causes=[
        RootCause(category="Biological", root_cause="Chronically elevated cortisol", sort_order=1),
        RootCause(category="Biological", root_cause="Disrupted sleep architecture", sort_order=2),
        RootCause(category="Biological", root_cause="Nervous system stuck in sympathetic ('fight or flight') dominance", sort_order=3),
        RootCause(category="Lifestyle", root_cause="Overcommitment / poor boundary-setting", sort_order=4),
        RootCause(category="Lifestyle", root_cause="Stimulant overuse (caffeine) masking fatigue signals", sort_order=5),
        RootCause(category="Psychological", root_cause="Inability to downshift / constant mental load", sort_order=6),
        RootCause(category="Psychological", root_cause="Guilt around rest ('I should be doing more')", sort_order=7),
    ],
    nutrition_targets=[
        NutritionTarget(field_name="Protein Target", field_value="90-110g per day", sort_order=1),
        NutritionTarget(field_name="Carb Strategy", field_value="Don't under-eat carbs — adequate carbs support cortisol regulation", sort_order=2),
        NutritionTarget(field_name="Fat Strategy", field_value="Moderate healthy fats; supports hormone production", sort_order=3),
        NutritionTarget(field_name="Meal Timing", field_value="Regular meals; avoid long fasting windows (added stress signal to the body)", sort_order=4),
        NutritionTarget(field_name="Caffeine Strategy", field_value="Cap intake; none after early afternoon", sort_order=5),
    ],
    foods=[
        Food(diet_type="vegetarian", food_type="Protein", options="Paneer, Greek yogurt, Tofu, Moong dal, Lentils, Chickpeas, Eggs", sort_order=1),
        Food(diet_type="vegetarian", food_type="Calming/Magnesium-rich", options="Spinach, Almonds, Pumpkin seeds, Dark chocolate (moderate)", sort_order=2),
        Food(diet_type="vegetarian", food_type="Carbs", options="Oats, Brown rice, Sweet potato, Quinoa", sort_order=3),
        Food(diet_type="vegetarian", food_type="Vegetables", options="Broccoli, Bell peppers, Leafy greens", sort_order=4),
        Food(diet_type="non_vegetarian", food_type="Protein", options="Eggs, Chicken (lean), Fish (salmon, sardines)", sort_order=1),
        Food(diet_type="non_vegetarian", food_type="Calming/Magnesium-rich", options="Salmon, Pumpkin seeds, Dark chocolate (moderate)", sort_order=2),
        Food(diet_type="non_vegetarian", food_type="Carbs", options="Oats, Brown rice, Sweet potato", sort_order=3),
        Food(diet_type="non_vegetarian", food_type="Vegetables", options="Broccoli, Bell peppers, Leafy greens", sort_order=4),
    ],
    exercises_recommended=[
        ExerciseRecommended(exercise_type="Walking (outdoors if possible)", frequency="Daily", duration="20-30 min", benefits="Direct cortisol reduction; nervous system reset", sort_order=1),
        ExerciseRecommended(exercise_type="Strength Training (moderate intensity)", frequency="3x/week", duration="30 min", benefits="Builds resilience without overloading stress response", sort_order=2),
        ExerciseRecommended(exercise_type="Yoga / Breathwork", frequency="Daily", duration="10-15 min", benefits="Activates parasympathetic ('rest and digest') response", sort_order=3),
        ExerciseRecommended(exercise_type="Mobility / Gentle Stretching", frequency="Daily", duration="10 min", benefits="Low-stress movement; supports recovery", sort_order=4),
    ],
    exercises_avoid=[
        ExerciseAvoid(exercise_type="Daily high-intensity HIIT", why_avoid="Compounds cortisol load on top of life stress", sort_order=1),
        ExerciseAvoid(exercise_type="Long endurance sessions (>60 min)", why_avoid="Increases stress hormone output further", sort_order=2),
        ExerciseAvoid(exercise_type="Training through visible burnout signs", why_avoid="Worsens fatigue, mood, and sleep", sort_order=3),
        ExerciseAvoid(exercise_type="Skipping rest days 'to stay disciplined'", why_avoid="Prevents nervous system recovery", sort_order=4),
    ],
    workout_routines=[
        WorkoutRoutine(
            time_minutes=15,
            location="any",
            routine_label="15-Minute Calm Strength Routine",
            exercises=[
                WorkoutExercise(exercise_name="Warm-up Walk", reps_or_time="3 min", rest="—", sort_order=1),
                WorkoutExercise(exercise_name="Box Breathing", reps_or_time="3 min", rest="—", sort_order=2),
                WorkoutExercise(exercise_name="Bodyweight Squats", reps_or_time="10 reps", rest="15 sec", sort_order=3),
                WorkoutExercise(exercise_name="Glute Bridges", reps_or_time="12 reps", rest="15 sec", sort_order=4),
                WorkoutExercise(exercise_name="Plank", reps_or_time="20 sec", rest="15 sec", sort_order=5),
                WorkoutExercise(exercise_name="Cool-down Stretch", reps_or_time="3 min", rest="—", sort_order=6),
            ],
            sort_order=1,
        ),
        WorkoutRoutine(
            time_minutes=30,
            location="any",
            routine_label="30-Minute Calm Strength Routine",
            exercises=[
                WorkoutExercise(exercise_name="Warm-up Walk", reps_or_time="5 min", rest="—", sort_order=1),
                WorkoutExercise(exercise_name="Goblet Squats", reps_or_time="10 reps", sets="3", rest="30 sec", sort_order=2),
                WorkoutExercise(exercise_name="Dumbbell Rows", reps_or_time="10 reps", sets="3", rest="30 sec", sort_order=3),
                WorkoutExercise(exercise_name="Glute Bridges", reps_or_time="12 reps", sets="3", rest="20 sec", sort_order=4),
                WorkoutExercise(exercise_name="Yoga / Breathwork Flow", reps_or_time="8 min", rest="—", sort_order=5),
                WorkoutExercise(exercise_name="Cool-down Stretch", reps_or_time="4 min", rest="—", sort_order=6),
            ],
            sort_order=2,
        ),
    ],
    constraints=[
        ModuleConstraint(constraint_name="High-stress day (depleted)", solution="Recovery mode", approach="15-min walk + breathwork only; skip strength that day", sort_order=1),
        ModuleConstraint(constraint_name="Home Workout", solution="Minimal equipment", approach="Bodyweight squats, Glute bridges, Plank, Breathwork", sort_order=2),
        ModuleConstraint(constraint_name="Gym Workout", solution="Moderate intensity only", approach="Goblet squats, Dumbbell rows, avoid max-effort lifts", sort_order=3),
        ModuleConstraint(constraint_name="Poor sleep night", solution="Reduce intensity, not skip entirely", approach="Walk + mobility instead of strength session", sort_order=4),
    ],
    habits=[
        Habit(habit_name="Breathwork", daily_target="10 min/day", how_to_track="Meditation app / journal", sort_order=1),
        Habit(habit_name="Sleep", daily_target="7-8 hours", how_to_track="Sleep app / journal", sort_order=2),
        Habit(habit_name="Caffeine Cutoff", daily_target="None after 2pm", how_to_track="Journal", sort_order=3),
        Habit(habit_name="Water", daily_target="2-3 liters", how_to_track="Water bottle with marks", sort_order=4),
        Habit(habit_name="Stress Check-in", daily_target="1x/day", how_to_track="Rate stress 1-10 in journal", sort_order=5),
        Habit(habit_name="Outdoor Time", daily_target="15-20 min/day", how_to_track="Walk log", sort_order=6),
    ],
    psychology_thoughts=[
        PsychologyThought(common_thought="I should be doing more.", emotional_impact="Guilt", solution="Reframe: recovery is productive; rest is part of the plan, not a failure of it", sort_order=1),
        PsychologyThought(common_thought="If I slow down, I'll lose progress.", emotional_impact="Anxiety", solution="Sustainable pace beats burnout-and-quit cycles every time", sort_order=2),
        PsychologyThought(common_thought="I can't switch my brain off.", emotional_impact="Overwhelm", solution="Daily breathwork trains the nervous system to downshift over time", sort_order=3),
        PsychologyThought(common_thought="I'm running on empty but can't stop.", emotional_impact="Exhaustion", solution="Build in non-negotiable recovery windows, even short ones", sort_order=4),
    ],
    plateau_actions=[
        PlateauAction(trigger_condition="Stress levels not improving (2+ weeks)", action_to_take="Add 1 extra rest day; increase breathwork to 2x/day", timeframe="Immediate", sort_order=1),
        PlateauAction(trigger_condition="Weight pause despite consistency", action_to_take="Check sleep and stress before changing food intake", timeframe="Immediate", sort_order=2),
        PlateauAction(trigger_condition="Energy drops further", action_to_take="Reduce training intensity, not frequency", timeframe="Immediate", sort_order=3),
        PlateauAction(trigger_condition="No results (4+ weeks)", action_to_take="Reassess sleep, stress, and recovery before changing diet", timeframe="Week 4", sort_order=4),
    ],
    faqs=[
        FAQ(question="Why doesn't harder training help my stress?", answer="Intense exercise is itself a stressor. Under chronic stress, it can add to the load rather than relieve it.", sort_order=1),
        FAQ(question="Should I still strength train?", answer="Yes, at moderate intensity — it builds resilience without overloading an already-stressed system.", sort_order=2),
        FAQ(question="Is it okay to skip a workout if I'm overwhelmed?", answer="Yes. A walk and breathwork on a depleted day is the better choice over pushing through.", sort_order=3),
        FAQ(question="Will this fix my stress?", answer="It won't remove external stressors, but it builds the body's capacity to recover from them.", sort_order=4),
    ],
    tracker_columns=[
        TrackerColumn(column_name="Weight", sort_order=1),
        TrackerColumn(column_name="Stress Level (1-10)", sort_order=2),
        TrackerColumn(column_name="Sleep (hrs)", sort_order=3),
        TrackerColumn(column_name="Energy (1-10)", sort_order=4),
        TrackerColumn(column_name="Mood (1-10)", sort_order=5),
        TrackerColumn(column_name="Notes", sort_order=6),
    ],
)
