"""EMOTIONAL EATING RESET — Claude-authored module.

Source: new_modules.md. Flagged is_authored_extension=True so it can be reviewed
and edited before going live without disturbing the 10 original-extracted modules.
"""
from models.module import (
    Emotion,
    FailedSolution,
    RootCause,
    NutritionTarget,
    Food,
    FoodToAvoid,
    MealIdea,
    ExerciseRecommended,
    ExerciseAvoid,
    WorkoutExercise,
    WorkoutRoutine,
    ModuleConstraint,
    Habit,
    PsychologyThought,
    PsychologyTechnique,
    PlateauAction,
    FAQ,
    TrackerColumn,
    KeyMetric,
    Module,
)


MODULE = Module(
    slug="emotional_eating_reset",
    display_name="Emotional Eating Reset",
    audience="Adults aged 20-50 who eat in response to stress, boredom, or sadness rather than hunger",
    primary_goal="Fat loss + food-mood independence + binge reduction",
    pain_level=8,
    urgency=7,
    main_barrier="Food is the only reliable coping tool; willpower-based diets ignore the trigger",
    is_authored_extension=True,
    content_pending=False,
    emotions=[
        Emotion(emotion="Guilt", exact_phrase="I ate my feelings again.", sort_order=1),
        Emotion(emotion="Shame", exact_phrase="I have no self-control around food.", sort_order=2),
        Emotion(emotion="Helplessness", exact_phrase="I don't even notice until the packet is empty.", sort_order=3),
        Emotion(emotion="Anxiety", exact_phrase="Stress eating at night", sort_order=4),
        Emotion(emotion="Loneliness", exact_phrase="Eating because I'm bored, not hungry", sort_order=5),
        Emotion(emotion="Self-Blame", exact_phrase="Why can't I just stop?", sort_order=6),
        Emotion(emotion="Despair", exact_phrase="I always end up back here.", sort_order=7),
        Emotion(emotion="Numbness", exact_phrase="Eating to feel nothing", sort_order=8),
    ],
    failed_solutions=[
        FailedSolution(solution_tried="Strict calorie deficit", why_it_failed="Restriction triggers bigger binges later", sort_order=1),
        FailedSolution(solution_tried="'Just use willpower' advice", why_it_failed="Ignores the emotional trigger; willpower runs out", sort_order=2),
        FailedSolution(solution_tried="Banning 'bad' foods", why_it_failed="Creates obsession; backfires into bingeing", sort_order=3),
        FailedSolution(solution_tried="Generic diet plans", why_it_failed="No emotional/behavioral component", sort_order=4),
        FailedSolution(solution_tried="Punishing workouts after a binge", why_it_failed="Reinforces shame cycle; worsens relationship with food", sort_order=5),
    ],
    root_causes=[
        RootCause(category="Psychological", root_cause="Food used as primary stress-regulation tool", sort_order=1),
        RootCause(category="Psychological", root_cause="Shame cycle (binge -> guilt -> restrict -> binge)", sort_order=2),
        RootCause(category="Psychological", root_cause="Low awareness of hunger vs. emotional triggers", sort_order=3),
        RootCause(category="Lifestyle", root_cause="No alternative coping mechanism built", sort_order=4),
        RootCause(category="Lifestyle", root_cause="Eating environment unmanaged (mindless eating cues)", sort_order=5),
        RootCause(category="Biological", root_cause="Blood sugar swings increasing cravings", sort_order=6),
        RootCause(category="Biological", root_cause="Poor sleep increasing emotional reactivity", sort_order=7),
    ],
    nutrition_targets=[
        NutritionTarget(field_name="Protein Target", field_value="90-110g per day (stabilizes blood sugar, reduces cravings)", sort_order=1),
        NutritionTarget(field_name="Fiber Target", field_value="25-30g per day", sort_order=2),
        NutritionTarget(field_name="Carb Strategy", field_value="Balanced, paired with protein at every meal to avoid blood sugar crashes", sort_order=3),
        NutritionTarget(field_name="Meal Timing", field_value="Regular 3 meals + 1 snack; never skip meals (skipping increases binge risk)", sort_order=4),
        NutritionTarget(field_name="Trigger-Food Strategy", field_value="No full bans; planned portions of trigger foods to remove 'forbidden' effect", sort_order=5),
    ],
    foods=[
        Food(diet_type="vegetarian", food_type="Protein", options="Paneer, Greek yogurt, Tofu, Moong dal, Lentils, Chickpeas, Eggs", sort_order=1),
        Food(diet_type="vegetarian", food_type="Carbs", options="Oats, Brown rice, Sweet potato, Whole wheat", sort_order=2),
        Food(diet_type="vegetarian", food_type="Fats", options="Almonds, Walnuts, Peanut butter, Olive oil", sort_order=3),
        Food(diet_type="vegetarian", food_type="Stabilizing Snacks", options="Greek yogurt + fruit, Roasted chana, Nuts", sort_order=4),
        Food(diet_type="non_vegetarian", food_type="Protein", options="Eggs, Chicken (lean), Fish (salmon, sardines)", sort_order=1),
        Food(diet_type="non_vegetarian", food_type="Carbs", options="Oats, Brown rice, Sweet potato", sort_order=2),
        Food(diet_type="non_vegetarian", food_type="Fats", options="Olive oil, Avocado, Walnuts", sort_order=3),
        Food(diet_type="non_vegetarian", food_type="Stabilizing Snacks", options="Boiled eggs, Protein smoothie, Nuts", sort_order=4),
    ],
    meal_ideas=[
        MealIdea(meal_time="Breakfast", diet_type="vegetarian", meal_option="Paneer bhurji + Oats + Fruit", sort_order=1),
        MealIdea(meal_time="Lunch", diet_type="vegetarian", meal_option="Moong dal + Brown rice + Sabzi + Yogurt", sort_order=2),
        MealIdea(meal_time="Dinner", diet_type="vegetarian", meal_option="Tofu stir-fry + Roti + Dal", sort_order=3),
        MealIdea(meal_time="Planned Treat", diet_type="vegetarian", meal_option="Small portion of trigger food, eaten seated, no screen", sort_order=4),
        MealIdea(meal_time="Breakfast", diet_type="non_vegetarian", meal_option="Eggs + Oats + Fruit", sort_order=1),
        MealIdea(meal_time="Lunch", diet_type="non_vegetarian", meal_option="Chicken curry + Brown rice + Vegetables", sort_order=2),
        MealIdea(meal_time="Dinner", diet_type="non_vegetarian", meal_option="Fish grilled + Sweet potato + Vegetables", sort_order=3),
        MealIdea(meal_time="Planned Treat", diet_type="non_vegetarian", meal_option="Small portion of trigger food, eaten seated, no screen", sort_order=4),
    ],
    exercises_recommended=[
        ExerciseRecommended(exercise_type="Walking", frequency="Daily", duration="20-30 min", benefits="Mood regulation; alternative to stress eating", sort_order=1),
        ExerciseRecommended(exercise_type="Strength Training", frequency="3x/week", duration="30 min", benefits="Builds confidence; structured outlet", sort_order=2),
        ExerciseRecommended(exercise_type="Yoga / Breathwork", frequency="Daily", duration="10-15 min", benefits="Direct nervous-system down-regulation; replaces the trigger response", sort_order=3),
        ExerciseRecommended(exercise_type="Light Movement (post-meal)", frequency="As needed", duration="5-10 min", benefits="Interrupts mindless second-helping cycles", sort_order=4),
    ],
    exercises_avoid=[
        ExerciseAvoid(exercise_type="Punishment cardio after eating", why_avoid="Reinforces guilt-driven exercise; worsens cycle", sort_order=1),
        ExerciseAvoid(exercise_type="Excessive HIIT", why_avoid="Raises cortisol, can increase appetite/cravings", sort_order=2),
        ExerciseAvoid(exercise_type="Skipping workouts as 'deserved punishment'", why_avoid="Strengthens shame loop", sort_order=3),
    ],
    workout_routines=[
        WorkoutRoutine(
            time_minutes=15,
            location="any",
            routine_label="15-Minute Reset Routine",
            exercises=[
                WorkoutExercise(exercise_name="Warm-up Walk", reps_or_time="2 min", rest="—", sort_order=1),
                WorkoutExercise(exercise_name="Body Squats", reps_or_time="12 reps", rest="10 sec", sort_order=2),
                WorkoutExercise(exercise_name="Push-ups (knees)", reps_or_time="8 reps", rest="10 sec", sort_order=3),
                WorkoutExercise(exercise_name="Glute Bridges", reps_or_time="12 reps", rest="10 sec", sort_order=4),
                WorkoutExercise(exercise_name="Box Breathing", reps_or_time="2 min", rest="—", sort_order=5),
                WorkoutExercise(exercise_name="Cool-down Stretch", reps_or_time="2 min", rest="—", sort_order=6),
            ],
            sort_order=1,
        ),
        WorkoutRoutine(
            time_minutes=30,
            location="any",
            routine_label="30-Minute Reset Routine",
            exercises=[
                WorkoutExercise(exercise_name="Warm-up Walk", reps_or_time="5 min", rest="—", sort_order=1),
                WorkoutExercise(exercise_name="Goblet Squats", reps_or_time="12 reps", sets="3", rest="30 sec", sort_order=2),
                WorkoutExercise(exercise_name="Dumbbell Rows", reps_or_time="10 reps", sets="3", rest="30 sec", sort_order=3),
                WorkoutExercise(exercise_name="Plank", reps_or_time="30 sec", sets="3", rest="20 sec", sort_order=4),
                WorkoutExercise(exercise_name="Breathwork / Yoga", reps_or_time="8 min", rest="—", sort_order=5),
                WorkoutExercise(exercise_name="Cool-down Stretch", reps_or_time="2 min", rest="—", sort_order=6),
            ],
            sort_order=2,
        ),
    ],
    constraints=[
        ModuleConstraint(constraint_name="Urge to binge (active)", solution="10-minute delay rule", approach="Walk + breathwork before any food decision", sort_order=1),
        ModuleConstraint(constraint_name="Home Workout", solution="Minimal equipment", approach="Body squats, Push-ups, Glute bridges, Plank", sort_order=2),
        ModuleConstraint(constraint_name="Gym Workout", solution="Full equipment access", approach="Goblet squats, Dumbbell rows, Machine work", sort_order=3),
        ModuleConstraint(constraint_name="Late-night cravings", solution="Replace, don't restrict", approach="Herbal tea + planned snack + brushing teeth ritual", sort_order=4),
        ModuleConstraint(constraint_name="Stressful day", solution="Trigger-substitute routine", approach="10 min walk + journaling before any eating decision", sort_order=5),
    ],
    habits=[
        Habit(habit_name="Hunger Check-in", daily_target="Before each meal", how_to_track="Rate hunger 1-10 in journal", sort_order=1),
        Habit(habit_name="Mood Journal", daily_target="1 entry/day", how_to_track="Note trigger, feeling, action taken", sort_order=2),
        Habit(habit_name="Sleep", daily_target="7-8 hours", how_to_track="Sleep app / journal", sort_order=3),
        Habit(habit_name="Water", daily_target="2-3 liters", how_to_track="Water bottle with marks", sort_order=4),
        Habit(habit_name="Planned Treat", daily_target="Once scheduled per day/week", how_to_track="Food tracker app", sort_order=5),
        Habit(habit_name="Pause Practice", daily_target="Before every snack", how_to_track="10-minute delay + 3 deep breaths", sort_order=6),
    ],
    psychology_thoughts=[
        PsychologyThought(common_thought="I have no self-control.", emotional_impact="Shame", solution="Reframe: this is a learned coping pattern, not a character flaw", sort_order=1),
        PsychologyThought(common_thought="I ruined my progress.", emotional_impact="Despair", solution="One meal doesn't erase progress; return to next planned meal", sort_order=2),
        PsychologyThought(common_thought="I always end up back here.", emotional_impact="Hopelessness", solution="Track triggers, not just food — pattern awareness breaks the cycle", sort_order=3),
        PsychologyThought(common_thought="I ate my feelings again.", emotional_impact="Guilt", solution="Name the feeling before naming the food: 'What did I actually need?'", sort_order=4),
        PsychologyThought(common_thought="Why can't I just stop?", emotional_impact="Self-blame", solution="Build a replacement ritual; willpower isn't the missing piece, a tool is", sort_order=5),
    ],
    psychology_techniques=[
        PsychologyTechnique(technique="Urge Surfing", how_to_apply="Notice the craving, wait 10 minutes, observe it peak and fade", sort_order=1),
        PsychologyTechnique(technique="Trigger Mapping", how_to_apply="Journal what preceded the urge (stress, boredom, loneliness)", sort_order=2),
        PsychologyTechnique(technique="Non-Food Coping Menu", how_to_apply="List of 5 go-to alternatives (walk, call a friend, shower, music, stretch)", sort_order=3),
        PsychologyTechnique(technique="Self-Compassion Reframe", how_to_apply="Replace 'I failed' with 'I'm learning my patterns'", sort_order=4),
        PsychologyTechnique(technique="Planned Permission", how_to_apply="Scheduling treats removes the 'forbidden fruit' intensity", sort_order=5),
    ],
    plateau_actions=[
        PlateauAction(trigger_condition="Binge frequency not dropping", action_to_take="Revisit trigger map; add one new coping tool", timeframe="Week 2-3", sort_order=1),
        PlateauAction(trigger_condition="Weight pause despite consistency", action_to_take="Check sleep + stress levels before changing food", timeframe="Immediate", sort_order=2),
        PlateauAction(trigger_condition="Mood worsens", action_to_take="Add daily breathwork; reduce self-monitoring intensity", timeframe="Immediate", sort_order=3),
        PlateauAction(trigger_condition="Relapse after 3+ weeks of progress", action_to_take="Normalize the setback; resume next planned meal, no 'restart Monday'", timeframe="Immediate", sort_order=4),
    ],
    faqs=[
        FAQ(question="Why do I eat when I'm not hungry?", answer="Food is functioning as an emotional regulator, not a hunger response. The goal is to build other regulation tools, not just restrict food.", sort_order=1),
        FAQ(question="Is it okay to still eat treats?", answer="Yes. Planned, portioned treats reduce binge risk more than total bans do.", sort_order=2),
        FAQ(question="What do I do during an urge to binge?", answer="Use the 10-minute delay rule: walk, breathe, journal — then decide.", sort_order=3),
        FAQ(question="Will this fix emotional eating completely?", answer="It's managed, not 'cured' overnight. Awareness + replacement habits reduce frequency and intensity over time.", sort_order=4),
        FAQ(question="Should I exercise after a binge?", answer="No punishment workouts. Normal scheduled movement only — exercise is not a penalty.", sort_order=5),
    ],
    tracker_columns=[
        TrackerColumn(column_name="Weight", sort_order=1),
        TrackerColumn(column_name="Binge Episodes", sort_order=2),
        TrackerColumn(column_name="Trigger Awareness (1-10)", sort_order=3),
        TrackerColumn(column_name="Mood (1-10)", sort_order=4),
        TrackerColumn(column_name="Sleep (hrs)", sort_order=5),
        TrackerColumn(column_name="Notes", sort_order=6),
    ],
    key_metrics=[
        KeyMetric(metric_name="Binge Episodes", target="Declining trend", why_important="Direct measure of progress", sort_order=1),
        KeyMetric(metric_name="Trigger Awareness", target="7+ average", why_important="Indicates pattern recognition improving", sort_order=2),
        KeyMetric(metric_name="Sleep Hours", target="7-8 hours", why_important="Poor sleep increases emotional eating risk", sort_order=3),
        KeyMetric(metric_name="Mood", target="6+ average", why_important="Stable mood reduces reliance on food for regulation", sort_order=4),
    ],
)
