"""Executive Energy (Working Professionals) — original module from fitness_database.docx.

Auto-generated from /tmp/fitness_database.docx by scripts/import_docx.py.
Every row below traces to a row in the source DOCX. No content invented.
"""
from models.module import (
    Emotion,
    ExerciseAvoid,
    ExerciseRecommended,
    FAQ,
    FailedSolution,
    Food,
    FoodToAvoid,
    Habit,
    KeyMetric,
    MealIdea,
    ModuleConstraint,
    NutritionTarget,
    PlateauAction,
    PsychologyTechnique,
    PsychologyThought,
    RootCause,
    TrackerColumn,
    WorkoutExercise,
    WorkoutRoutine,
    Module,
)


MODULE = Module(
    slug="executive_energy",
    display_name="Executive Energy (Working Professionals)",
    audience="Working professionals aged 25-45, high-stress jobs",
    primary_goal="Fat loss + energy boost + career performance",
    main_barrier="Too tired; no time; packed schedule; stress not accounted for",
    pain_level=8,
    urgency=8,
    is_authored_extension=False,
    content_pending=False,
    emotions=[
    Emotion(emotion="Exhaustion", exact_phrase="Too tired to work out", sort_order=1),
    Emotion(emotion="Time Struggle", exact_phrase="no time", sort_order=2),
    Emotion(emotion="Time Struggle", exact_phrase="packed schedule", sort_order=3),
    Emotion(emotion="Mental Overload", exact_phrase="mind running at full speed", sort_order=4),
    Emotion(emotion="Exhaustion", exact_phrase="overtired", sort_order=5),
    Emotion(emotion="Stress", exact_phrase="overstressed", sort_order=6),
    Emotion(emotion="Physical Pain", exact_phrase="tech neck, posture problems", sort_order=7),
    Emotion(emotion="Shame", exact_phrase="Burnout shame", sort_order=8),
    Emotion(emotion="Failure", exact_phrase="feeling like a failure for not maintaining health", sort_order=9),
    Emotion(emotion="Stress", exact_phrase="stress about long-term consequences", sort_order=10),
    Emotion(emotion="Guilt", exact_phrase="guilt spending time on self", sort_order=11),
],
    failed_solutions=[
    FailedSolution(solution_tried="HIIT workouts", why_it_failed="Too exhausting; drains energy; increases burnout", sort_order=1),
    FailedSolution(solution_tried="Early morning (6 AM)", why_it_failed="Can't wake up; sleep deprivation; impossible", sort_order=2),
    FailedSolution(solution_tried="Evening gym", why_it_failed="Too tired after work; burnout; no motivation", sort_order=3),
    FailedSolution(solution_tried="Weekend workouts", why_it_failed="Too busy; family/time conflicts; skipped", sort_order=4),
    FailedSolution(solution_tried="Corporate wellness programs", why_it_failed="Generic; not flexible; ignore energy levels", sort_order=5),
    FailedSolution(solution_tried="Generic fitness apps", why_it_failed="No energy-level adjustments; stress not accounted", sort_order=6),
    FailedSolution(solution_tried="Executive coaches (limited)", why_it_failed="Limited availability; expensive; not personalized", sort_order=7),
],
    root_causes=[
    RootCause(category="Lifestyle", root_cause="Packed schedule (work + meetings + deadlines)", sort_order=1),
    RootCause(category="Lifestyle", root_cause="Chronic stress (high-pressure job)", sort_order=2),
    RootCause(category="Lifestyle", root_cause="Poor sleep quality (late nights, screens)", sort_order=3),
    RootCause(category="Lifestyle", root_cause="Sedentary work (desk jobs, tech neck)", sort_order=4),
    RootCause(category="Lifestyle", root_cause="Posture problems (desk work, poor ergonomics)", sort_order=5),
    RootCause(category="Lifestyle", root_cause="No flexible scheduling options", sort_order=6),
    RootCause(category="Psychological", root_cause="Burnout shame", sort_order=7),
    RootCause(category="Psychological", root_cause="Feeling like a failure", sort_order=8),
    RootCause(category="Psychological", root_cause="Stress about long-term health", sort_order=9),
    RootCause(category="Psychological", root_cause="Guilt spending time on self", sort_order=10),
    RootCause(category="Psychological", root_cause="Low self-confidence", sort_order=11),
    RootCause(category="Biological", root_cause="High cortisol (chronic stress)", sort_order=12),
    RootCause(category="Biological", root_cause="Mental fatigue (mind running full speed)", sort_order=13),
    RootCause(category="Biological", root_cause="Physical fatigue (overtired body)", sort_order=14),
],
    nutrition_targets=[
    NutritionTarget(field_name="Field", field_value="Details", sort_order=1),
    NutritionTarget(field_name="Protein Target", field_value="100-120g per day", sort_order=2),
    NutritionTarget(field_name="Fiber Target", field_value="25-35g per day", sort_order=3),
    NutritionTarget(field_name="Carb Strategy", field_value="Moderate, focus on complex carbs (energy for work)", sort_order=4),
    NutritionTarget(field_name="Fat Strategy", field_value="Moderate healthy fats (brain function)", sort_order=5),
    NutritionTarget(field_name="Meal Timing", field_value="Quick meals; office-friendly; no elaborate prep", sort_order=6),
    NutritionTarget(field_name="Prep Strategy", field_value="15-min meals; grab-and-go options", sort_order=7),
],
    foods=[
    Food(diet_type="vegetarian", food_type="Protein", options="Paneer, Greek yogurt, Tofu, Moong dal, Lentils, Chickpeas, Eggs", sort_order=1),
    Food(diet_type="vegetarian", food_type="Carbs", options="Quinoa, Brown rice, Sweet potato, Oats, Whole wheat", sort_order=2),
    Food(diet_type="vegetarian", food_type="Fats", options="Olive oil, Coconut, Almonds, Walnuts, Flax seeds", sort_order=3),
    Food(diet_type="vegetarian", food_type="Vegetables", options="Spinach, Broccoli, Cauliflower, Bell peppers, Zucchini", sort_order=4),
    Food(diet_type="vegetarian", food_type="Office-Friendly", options="Protein bars, Greek yogurt, Nuts, Fruit", sort_order=5),
    Food(diet_type="non_vegetarian", food_type="Protein", options="Eggs, Chicken (lean), Fish (salmon, sardines), Shrimp", sort_order=1),
    Food(diet_type="non_vegetarian", food_type="Carbs", options="Quinoa, Brown rice, Sweet potato, Whole wheat", sort_order=2),
    Food(diet_type="non_vegetarian", food_type="Fats", options="Olive oil, Avocado, Walnuts", sort_order=3),
    Food(diet_type="non_vegetarian", food_type="Vegetables", options="Same as vegetarian", sort_order=4),
    Food(diet_type="non_vegetarian", food_type="Office-Friendly", options="Protein shakes, Eggs, Chicken salad, Fish", sort_order=5),
],
    foods_to_avoid=[
    FoodToAvoid(food_type="Processed sugar", why_avoid="Energy crashes; brain fog; fatigue", sort_order=1),
    FoodToAvoid(food_type="Refined carbs", why_avoid="Blood sugar spikes; mental fatigue", sort_order=2),
    FoodToAvoid(food_type="Excessive caffeine", why_avoid="Increases cortisol; worsens burnout", sort_order=3),
    FoodToAvoid(food_type="Alcohol", why_avoid="Increases inflammation; poor sleep; burnout", sort_order=4),
    FoodToAvoid(food_type="Heavy meals", why_avoid="Slows energy; brain fog; office discomfort", sort_order=5),
],
    meal_ideas=[
    MealIdea(meal_time="Breakfast", diet_type="vegetarian", meal_option="Paneer bhurji + 2 rotis + Yogurt", sort_order=1),
    MealIdea(meal_time="Breakfast", diet_type="non_vegetarian", meal_option="Eggs + 2 rotis + Spinach + Coffee", sort_order=2),
    MealIdea(meal_time="Lunch", diet_type="vegetarian", meal_option="Moong dal + Brown rice + Sabzi + Yogurt", sort_order=3),
    MealIdea(meal_time="Lunch", diet_type="non_vegetarian", meal_option="Chicken salad + Quinoa + Vegetables", sort_order=4),
    MealIdea(meal_time="Dinner", diet_type="vegetarian", meal_option="Tofu stir-fry + Roti + Dal", sort_order=5),
    MealIdea(meal_time="Dinner", diet_type="non_vegetarian", meal_option="Fish grilled + Sweet potato + Broccoli", sort_order=6),
    MealIdea(meal_time="Snacks", diet_type="vegetarian", meal_option="Greek yogurt + Berries, Almonds, Protein bar", sort_order=7),
    MealIdea(meal_time="Snacks", diet_type="non_vegetarian", meal_option="Protein shake, Eggs, Chicken strips", sort_order=8),
    MealIdea(meal_time="Office Grab", diet_type="vegetarian", meal_option="Nuts, Fruit, Protein bar, Yogurt", sort_order=9),
    MealIdea(meal_time="Office Grab", diet_type="non_vegetarian", meal_option="Protein shake, Eggs, Chicken salad", sort_order=10),
],
    exercises_recommended=[
    ExerciseRecommended(exercise_type="Walking", frequency="Daily", duration="15-20 min", benefits="Low stress, boosts energy, fits into workday", sort_order=1),
    ExerciseRecommended(exercise_type="Strength Training", frequency="3x/week", duration="20-25 min", benefits="Builds muscle, boosts energy; office-friendly", sort_order=2),
    ExerciseRecommended(exercise_type="Yoga", frequency="2-3x/week", duration="15-20 min", benefits="Reduces cortisol, improves posture; desk-friendly", sort_order=3),
    ExerciseRecommended(exercise_type="Pilates", frequency="2x/week", duration="20 min", benefits="Core strength, posture correction; home/office", sort_order=4),
    ExerciseRecommended(exercise_type="Desk Exercises", frequency="Daily", duration="5-10 min", benefits="Tech neck relief; no equipment; at desk", sort_order=5),
    ExerciseRecommended(exercise_type="Resistance Bands", frequency="2-3x/week", duration="15 min", benefits="Office-friendly; quiet; minimal space", sort_order=6),
],
    exercises_avoid=[
    ExerciseAvoid(exercise_type="HIIT workouts", why_avoid="Too exhausting; increases burnout; drains energy", sort_order=1),
    ExerciseAvoid(exercise_type="60-minute gym classes", why_avoid="Too long; no time; schedule conflicts", sort_order=2),
    ExerciseAvoid(exercise_type="Early morning (6 AM)", why_avoid="Can't wake up; sleep deprivation", sort_order=3),
    ExerciseAvoid(exercise_type="Late evening (after 9 PM)", why_avoid="Too tired; burnout; no motivation", sort_order=4),
    ExerciseAvoid(exercise_type="High-impact jumping", why_avoid="Noisy; office not suitable; exhaustion", sort_order=5),
    ExerciseAvoid(exercise_type="Overtraining", why_avoid="Worsens burnout; increases cortisol", sort_order=6),
],
    workout_routines=[
    WorkoutRoutine(
        time_minutes=15,
        location="any",
        routine_label="Routine A",
        exercises=[
            WorkoutExercise(exercise_name="Warm-up Walk", reps_or_time="3 min", rest="—", sort_order=1),
            WorkoutExercise(exercise_name="Body Squats", reps_or_time="12 reps x 2 sets", rest="20 sec", sort_order=2),
            WorkoutExercise(exercise_name="Push-ups (knees)", reps_or_time="8 reps x 2 sets", rest="20 sec", sort_order=3),
            WorkoutExercise(exercise_name="Glute Bridges", reps_or_time="12 reps x 2 sets", rest="20 sec", sort_order=4),
            WorkoutExercise(exercise_name="Plank", reps_or_time="20 sec x 2 sets", rest="20 sec", sort_order=5),
            WorkoutExercise(exercise_name="Standing Knee Raises", reps_or_time="10 reps x 2 sets", rest="20 sec", sort_order=6),
            WorkoutExercise(exercise_name="Cool-down Stretch", reps_or_time="2 min", rest="—", sort_order=7),
        ],
    ),
    WorkoutRoutine(
        time_minutes=30,
        location="any",
        routine_label="Routine C",
        exercises=[
            WorkoutExercise(exercise_name="Warm-up Walk", reps_or_time="5 min", rest="—", sort_order=1),
            WorkoutExercise(exercise_name="Squat to Press", reps_or_time="8 reps x 3 sets", rest="30 sec", sort_order=2),
            WorkoutExercise(exercise_name="Bent-over Rows", reps_or_time="10 reps x 3 sets", rest="30 sec", sort_order=3),
            WorkoutExercise(exercise_name="Lunges", reps_or_time="8 reps each x 2 sets", rest="30 sec", sort_order=4),
            WorkoutExercise(exercise_name="Push-ups", reps_or_time="8 reps x 3 sets", rest="30 sec", sort_order=5),
            WorkoutExercise(exercise_name="Plank", reps_or_time="30 sec x 2 sets", rest="20 sec", sort_order=6),
            WorkoutExercise(exercise_name="Cool-down Stretch", reps_or_time="5 min", rest="—", sort_order=7),
        ],
    ),
],
    constraints=[
    ModuleConstraint(constraint_name="Office Workout", solution="Use desk/minimal equipment", approach="Desk exercises, Resistance bands, Seated movements", sort_order=1),
    ModuleConstraint(constraint_name="Busy Schedule", solution="15-minute version", approach="Routine A = 15 min; do between meetings", sort_order=2),
    ModuleConstraint(constraint_name="No Time (5 min)", solution="Minimum viable workout", approach="5-min desk routine; at workstation", sort_order=3),
    ModuleConstraint(constraint_name="Fatigue Day", solution="Recovery mode", approach="10 min walk + 5 min yoga + stretching only", sort_order=4),
    ModuleConstraint(constraint_name="High Stress Day", solution="Stress-reduction mode", approach="Yoga only; no strength training; breathing focus", sort_order=5),
    ModuleConstraint(constraint_name="Late Meetings", solution="Flexible timing", approach="Do workout before/after; no fixed schedule", sort_order=6),
    ModuleConstraint(constraint_name="Travel Days", solution="Hotel-friendly", approach="Bodyweight only; resistance bands; no gym needed", sort_order=7),
    ModuleConstraint(constraint_name="Posture Problems", solution="Correction focus", approach="Yoga + Pilates; tech neck relief exercises", sort_order=8),
],
    habits=[
    Habit(habit_name="Habit", daily_target="Daily Target", how_to_track="How to Track", sort_order=1),
    Habit(habit_name="Sleep", daily_target="7-8 hours", how_to_track="Sleep app / journal", sort_order=2),
    Habit(habit_name="Water", daily_target="2-3 liters", how_to_track="Water bottle with marks", sort_order=3),
    Habit(habit_name="Step Goals", daily_target="6,000 steps", how_to_track="Step counter / phone", sort_order=4),
    Habit(habit_name="Stress Reduction", daily_target="10 min/day", how_to_track="Meditation app / breathing", sort_order=5),
    Habit(habit_name="Morning Routine", daily_target="10 min", how_to_track="Journal + stretch + water", sort_order=6),
    Habit(habit_name="Protein Intake", daily_target="100-120g", how_to_track="Food tracker app", sort_order=7),
    Habit(habit_name="Evening Walk", daily_target="15 min", how_to_track="After work walk", sort_order=8),
    Habit(habit_name="Screen Time", daily_target="Reduce before bed", how_to_track="No screens 1 hr before sleep", sort_order=9),
    Habit(habit_name="Desk Breaks", daily_target="Every 2 hours", how_to_track="Move/stretch 5 min", sort_order=10),
],
    psychology_thoughts=[
    PsychologyThought(common_thought="I'm a failure.", emotional_impact="Burnout shame", solution='Reframe: "Workouts boost career performance"', sort_order=1),
    PsychologyThought(common_thought="I always fail.", emotional_impact="Self-trust broken", solution="Habit stacking + micro-goals (5-15 min)", sort_order=2),
    PsychologyThought(common_thought="I'm broken.", emotional_impact="Feeling unfixable", solution="Education on energy-based fitness", sort_order=3),
    PsychologyThought(common_thought="I have no discipline.", emotional_impact="Shame cycle", solution="Minimum viable workouts (5 min at desk)", sort_order=4),
    PsychologyThought(common_thought="Spending time on self is guilty.", emotional_impact="Guilt", solution='Reframe: "Self-care = better work performance"', sort_order=5),
    PsychologyThought(common_thought="Everyone else succeeds.", emotional_impact="Comparison pain", solution="Focus on YOUR energy, not others", sort_order=6),
    PsychologyThought(common_thought="I quit too easily.", emotional_impact="Self-blame", solution='Identity change: "I\'m someone who fuels my career"', sort_order=7),
    PsychologyThought(common_thought="I don't have time.", emotional_impact="overwhelm", solution="Time-blocking + 5-15 min routines", sort_order=8),
    PsychologyThought(common_thought="Workouts drain me.", emotional_impact="Exhaustion fear", solution="Energy-based approach; workouts BOOST energy", sort_order=9),
],
    psychology_techniques=[
    PsychologyTechnique(technique="Habit Stacking", how_to_apply="Attach workout to existing habit (e.g., after morning meeting)", sort_order=1),
    PsychologyTechnique(technique="Minimum Viable Workouts", how_to_apply="5-min desk routine = still counts as showing up", sort_order=2),
    PsychologyTechnique(technique="Identity Change", how_to_apply='Daily phrase: "I\'m someone who fuels my career with energy"', sort_order=3),
    PsychologyTechnique(technique="Progress Tracking", how_to_apply="Track energy + focus, not just weight", sort_order=4),
    PsychologyTechnique(technique="Reframe Failure", how_to_apply='"Quitting" → "I\'m learning what fuels MY career"', sort_order=5),
    PsychologyTechnique(technique="Career Connection", how_to_apply="Link fitness to work performance (productivity)", sort_order=6),
],
    plateau_actions=[
    PlateauAction(trigger_condition="Weight pause (2+ weeks)", action_to_take="Increase protein by 10-15g", timeframe="Immediate", sort_order=1),
    PlateauAction(trigger_condition="Weight pause (2+ weeks)", action_to_take="Increase steps by 1,000/day", timeframe="Immediate", sort_order=2),
    PlateauAction(trigger_condition="Weight pause (2+ weeks)", action_to_take="Add 1 rest day/week (more recovery)", timeframe="Week 3-4", sort_order=3),
    PlateauAction(trigger_condition="Weight pause (2+ weeks)", action_to_take="Stress management (meditation 10 min/day)", timeframe="Daily", sort_order=4),
    PlateauAction(trigger_condition="Energy drops", action_to_take="Add 1-2 rest days/week", timeframe="Immediate", sort_order=5),
    PlateauAction(trigger_condition="Mood worsens", action_to_take="Reduce intensity; increase yoga", timeframe="Immediate", sort_order=6),
    PlateauAction(trigger_condition="No results (4+ weeks)", action_to_take="Reassess calorie intake (don't crash diet)", timeframe="Week 4", sort_order=7),
    PlateauAction(trigger_condition="No results (4+ weeks)", action_to_take="Check sleep quality + stress levels", timeframe="Week 4", sort_order=8),
    PlateauAction(trigger_condition="No results (4+ weeks)", action_to_take="Adjust meeting schedule (more workout time)", timeframe="Week 4", sort_order=9),
],
    faqs=[
    FAQ(question="Why am I not losing weight?", answer='Professional life = chronic stress + poor sleep + packed schedule. Standard "make time" advice doesn\'t work. Need energy-based, flexible approach.', sort_order=1),
    FAQ(question="Can I eat rice?", answer="Yes, choose brown rice/quinoa. Limit to 1/2 cup per meal. Pair with protein + fiber. Office-friendly options available.", sort_order=2),
    FAQ(question="Should I do cardio?", answer="Yes, but LOW-INTENSITY only (walking). Avoid HIIT (too exhausting; increases burnout). Walk between meetings.", sort_order=3),
    FAQ(question="Is fasting good for professionals?", answer="Generally NO. Intermittent fasting can worsen energy/focus. Focus on consistent meals with protein. Office snacks = protein bars.", sort_order=4),
    FAQ(question="How much protein do I need?", answer="100-120g per day for fat loss + muscle retention + energy for work. Office snacks: protein bars, nuts, Greek yogurt.", sort_order=5),
    FAQ(question="Will strength training make me bulky?", answer="No. Strength training builds lean muscle, boosts energy. 20-min sessions are effective and not exhausting.", sort_order=6),
    FAQ(question="Can I exercise if I'm tired?", answer="YES. Energy-based approach: 5-min desk routine on fatigue days. Workouts BOOST energy, not drain it.", sort_order=7),
    FAQ(question="How often should I workout?", answer="3x 20-min strength training, daily walking (15 min), 2-3x yoga (15 min). Rest 3-4 days/week. Flexible scheduling.", sort_order=8),
    FAQ(question="What if I'm too tired?", answer="Do 5-min desk routine + 10-min walk. Rest is priority. Low-intensity only on burnout days.", sort_order=9),
    FAQ(question="Is executive fitness fixable?", answer='Not "cured" but MANAGED. Work WITH career life, not against it. Results come with energy-based consistency.', sort_order=10),
    FAQ(question="How do I find time?", answer="5-min desk routine between meetings; 15-min workout before/after work; walking lunch. No 60-min classes needed.", sort_order=11),
    FAQ(question="Do I need gym equipment?", answer="NO. All office/home-based; minimal equipment (resistance bands optional). Desk exercises included.", sort_order=12),
    FAQ(question="How does this help my career?", answer="Workouts BOOST energy + focus = better performance. Stress reduction = clearer thinking. Productivity increases.", sort_order=13),
],
    tracker_columns=[
    TrackerColumn(column_name="Weight", sort_order=1),
    TrackerColumn(column_name="Body Measurements", sort_order=2),
    TrackerColumn(column_name="Photos", sort_order=3),
    TrackerColumn(column_name="Energy Level (1-10)", sort_order=4),
    TrackerColumn(column_name="Focus Level (1-10)", sort_order=5),
    TrackerColumn(column_name="Steps/Day", sort_order=6),
    TrackerColumn(column_name="Protein (g)", sort_order=7),
    TrackerColumn(column_name="Burnout Level (1-10)", sort_order=8),
    TrackerColumn(column_name="Notes", sort_order=9),
],
    key_metrics=[
    KeyMetric(metric_name="Energy Level", target="7+ average", why_important="Indicates fitness BOOSTING energy (not draining)", sort_order=1),
    KeyMetric(metric_name="Focus Level", target="7+ average", why_important="Indicates better work performance", sort_order=2),
    KeyMetric(metric_name="Steps/Day", target="6,000 steps", why_important="Improves metabolism; walk between meetings", sort_order=3),
    KeyMetric(metric_name="Protein (g)", target="100-120g", why_important="Supports muscle + fat loss + energy", sort_order=4),
    KeyMetric(metric_name="Sleep Hours", target="7-8 hours", why_important="Critical for energy; burnout prevention", sort_order=5),
    KeyMetric(metric_name="Workout Consistency", target="3x/week (20 min)", why_important="Builds habit; manageable for busy schedule", sort_order=6),
    KeyMetric(metric_name="Burnout Level", target="Low (1-3/10)", why_important="High burnout = worse performance", sort_order=7),
],
)
