"""KNEE-SAFE STRENGTH — Claude-authored module.

Source: new_modules.md. Flagged is_authored_extension=True.
"""
from models.module import (
    Emotion,
    FailedSolution,
    RootCause,
    NutritionTarget,
    Food,
    ExerciseRecommended,
    ExerciseAvoid,
    WorkoutExercise,
    WorkoutRoutine,
    ModuleConstraint,
    Habit,
    PsychologyThought,
    PlateauAction,
    FAQ,
    TrackerColumn,
    Module,
)


MODULE = Module(
    slug="knee_safe_strength",
    display_name="Knee-Safe Strength",
    audience="Adults aged 25-55 with chronic or activity-related knee pain wanting to train safely",
    primary_goal="Fat loss / muscle gain without aggravating the knee",
    pain_level=7,
    urgency=7,
    main_barrier="Standard leg exercises (squats, lunges, jumping) cause pain; fear of making it worse",
    is_authored_extension=True,
    content_pending=False,
    emotions=[
        Emotion(emotion="Frustration", exact_phrase="Every program has squats and lunges.", sort_order=1),
        Emotion(emotion="Fear", exact_phrase="I'm scared I'll damage my knee more.", sort_order=2),
        Emotion(emotion="Discouragement", exact_phrase="I can't do what everyone else is doing.", sort_order=3),
        Emotion(emotion="Anxiety", exact_phrase="Will this ever stop hurting?", sort_order=4),
        Emotion(emotion="Shame", exact_phrase="I feel weak avoiding leg day.", sort_order=5),
        Emotion(emotion="Helplessness", exact_phrase="Nothing online accounts for bad knees.", sort_order=6),
    ],
    failed_solutions=[
        FailedSolution(solution_tried="Generic workout programs", why_it_failed="Default to squats/lunges/jump exercises; aggravate the knee", sort_order=1),
        FailedSolution(solution_tried="Pushing through the pain", why_it_failed="Worsens inflammation; sets back progress weeks", sort_order=2),
        FailedSolution(solution_tried="Complete avoidance of leg training", why_it_failed="Muscle loss around the joint; knee gets weaker, not better", sort_order=3),
        FailedSolution(solution_tried="Random YouTube 'knee-friendly' videos", why_it_failed="Inconsistent quality; no progression; not personalized", sort_order=4),
        FailedSolution(solution_tried="Over-reliance on painkillers to train", why_it_failed="Masks pain signal; risk of further injury", sort_order=5),
    ],
    root_causes=[
        RootCause(category="Biological", root_cause="Weak supporting muscles (quads, glutes, hamstrings) around the joint", sort_order=1),
        RootCause(category="Biological", root_cause="Poor joint tracking / alignment under load", sort_order=2),
        RootCause(category="Biological", root_cause="Existing inflammation or prior injury", sort_order=3),
        RootCause(category="Lifestyle", root_cause="Sedentary periods reducing joint mobility", sort_order=4),
        RootCause(category="Lifestyle", root_cause="Footwear or surface issues during activity", sort_order=5),
        RootCause(category="Psychological", root_cause="Fear-avoidance (avoiding all leg work, which weakens the joint further)", sort_order=6),
    ],
    nutrition_targets=[
        NutritionTarget(field_name="Protein Target", field_value="100-120g per day (supports muscle around the joint)", sort_order=1),
        NutritionTarget(field_name="Anti-inflammatory Focus", field_value="Omega-3s, turmeric, ginger, colorful vegetables", sort_order=2),
        NutritionTarget(field_name="Fat Strategy", field_value="Moderate healthy fats, anti-inflammatory sources prioritized", sort_order=3),
        NutritionTarget(field_name="Hydration", field_value="2.5-3 liters/day (joint tissue health)", sort_order=4),
    ],
    foods=[
        Food(diet_type="vegetarian", food_type="Protein", options="Paneer, Greek yogurt, Tofu, Moong dal, Lentils, Chickpeas, Eggs", sort_order=1),
        Food(diet_type="vegetarian", food_type="Anti-inflammatory", options="Turmeric, Ginger, Walnuts, Flax seeds, Green tea", sort_order=2),
        Food(diet_type="vegetarian", food_type="Carbs", options="Quinoa, Brown rice, Sweet potato, Oats", sort_order=3),
        Food(diet_type="vegetarian", food_type="Vegetables", options="Spinach, Broccoli, Bell peppers, Berries", sort_order=4),
        Food(diet_type="non_vegetarian", food_type="Protein", options="Eggs, Chicken (lean), Fish (salmon, sardines)", sort_order=1),
        Food(diet_type="non_vegetarian", food_type="Anti-inflammatory", options="Salmon (omega-3), Sardines, Turmeric, Ginger", sort_order=2),
        Food(diet_type="non_vegetarian", food_type="Carbs", options="Quinoa, Brown rice, Sweet potato", sort_order=3),
        Food(diet_type="non_vegetarian", food_type="Vegetables", options="Spinach, Broccoli, Bell peppers, Berries", sort_order=4),
    ],
    exercises_recommended=[
        ExerciseRecommended(exercise_type="Walking (flat surface)", frequency="Daily", duration="20-30 min", benefits="Low-impact joint-friendly cardio", sort_order=1),
        ExerciseRecommended(exercise_type="Seated/Supported Strength", frequency="3x/week", duration="30 min", benefits="Builds knee-supporting muscle without joint stress", sort_order=2),
        ExerciseRecommended(exercise_type="Swimming / Water-based", frequency="1-2x/week", duration="30 min", benefits="Zero-impact, full-body, joint-safe", sort_order=3),
        ExerciseRecommended(exercise_type="Upper Body + Core Focus", frequency="2x/week", duration="20-30 min", benefits="Maintains overall training while knee recovers", sort_order=4),
        ExerciseRecommended(exercise_type="Mobility / Stretching", frequency="Daily", duration="10 min", benefits="Maintains joint range of motion", sort_order=5),
    ],
    exercises_avoid=[
        ExerciseAvoid(exercise_type="Deep squats / lunges (loaded)", why_avoid="Increases shear force on the knee joint", sort_order=1),
        ExerciseAvoid(exercise_type="Jumping / plyometrics", why_avoid="High impact load on a compromised joint", sort_order=2),
        ExerciseAvoid(exercise_type="Running on hard surfaces", why_avoid="Repetitive impact stress", sort_order=3),
        ExerciseAvoid(exercise_type="Leg extensions with heavy load (if irritated)", why_avoid="Can aggravate patellofemoral pain", sort_order=4),
    ],
    workout_routines=[
        WorkoutRoutine(
            time_minutes=15,
            location="any",
            routine_label="15-Minute Knee-Safe Routine",
            exercises=[
                WorkoutExercise(exercise_name="Warm-up Walk", reps_or_time="3 min", rest="—", sort_order=1),
                WorkoutExercise(exercise_name="Seated Leg Extensions (light)", reps_or_time="12 reps", rest="15 sec", sort_order=2),
                WorkoutExercise(exercise_name="Wall Sit (pain-free range only)", reps_or_time="15-20 sec", rest="15 sec", sort_order=3),
                WorkoutExercise(exercise_name="Glute Bridges", reps_or_time="12 reps", rest="10 sec", sort_order=4),
                WorkoutExercise(exercise_name="Standing Resistance Band Rows", reps_or_time="12 reps", rest="10 sec", sort_order=5),
                WorkoutExercise(exercise_name="Seated Calf Raises", reps_or_time="15 reps", rest="10 sec", sort_order=6),
                WorkoutExercise(exercise_name="Cool-down Stretch", reps_or_time="3 min", rest="—", sort_order=7),
            ],
            sort_order=1,
        ),
        WorkoutRoutine(
            time_minutes=30,
            location="any",
            routine_label="30-Minute Knee-Safe Routine",
            exercises=[
                WorkoutExercise(exercise_name="Warm-up Walk", reps_or_time="5 min", rest="—", sort_order=1),
                WorkoutExercise(exercise_name="Leg Press (light, pain-free range)", reps_or_time="12 reps", sets="3", rest="30 sec", sort_order=2),
                WorkoutExercise(exercise_name="Seated Leg Extensions", reps_or_time="12 reps", sets="3", rest="30 sec", sort_order=3),
                WorkoutExercise(exercise_name="Glute Bridges", reps_or_time="15 reps", sets="3", rest="20 sec", sort_order=4),
                WorkoutExercise(exercise_name="Dumbbell Rows", reps_or_time="10 reps", sets="3", rest="30 sec", sort_order=5),
                WorkoutExercise(exercise_name="Overhead Press", reps_or_time="10 reps", sets="3", rest="30 sec", sort_order=6),
                WorkoutExercise(exercise_name="Cool-down Stretch", reps_or_time="5 min", rest="—", sort_order=7),
            ],
            sort_order=2,
        ),
    ],
    constraints=[
        ModuleConstraint(constraint_name="Knee Pain (active flare)", solution="Gentle movement only", approach="Walking + seated upper body + stretching", sort_order=1),
        ModuleConstraint(constraint_name="Home Workout", solution="Bodyweight/band-based knee-safe options", approach="Glute bridges, Resistance bands, Wall sits", sort_order=2),
        ModuleConstraint(constraint_name="Gym Workout", solution="Machine-based, controlled range", approach="Leg press, Leg extensions (light), Seated machines", sort_order=3),
        ModuleConstraint(constraint_name="Stairs/Impact-heavy job", solution="Reduce daily load where possible", approach="Schedule walking breaks; avoid double leg sessions same day", sort_order=4),
    ],
    habits=[
        Habit(habit_name="Pain Check-in", daily_target="Before/after each session", how_to_track="Rate pain 1-10 in journal", sort_order=1),
        Habit(habit_name="Mobility Work", daily_target="10 min/day", how_to_track="Stretch journal / app", sort_order=2),
        Habit(habit_name="Protein Intake", daily_target="100-120g", how_to_track="Food tracker app", sort_order=3),
        Habit(habit_name="Step Goals", daily_target="5,000-7,000 steps (flat terrain)", how_to_track="Step counter", sort_order=4),
        Habit(habit_name="Water", daily_target="2.5-3 liters", how_to_track="Water bottle with marks", sort_order=5),
    ],
    psychology_thoughts=[
        PsychologyThought(common_thought="I'll never train legs again.", emotional_impact="Hopelessness", solution="Reframe: training around it now builds toward training through it later", sort_order=1),
        PsychologyThought(common_thought="I'm weak for skipping squats.", emotional_impact="Shame", solution="Knee-safe strength work still builds real muscle and protects the joint", sort_order=2),
        PsychologyThought(common_thought="Pain means I'm making it worse.", emotional_impact="Fear", solution="Mild discomfort is normal; sharp/worsening pain is the actual stop signal", sort_order=3),
        PsychologyThought(common_thought="Nothing is made for people like me.", emotional_impact="Isolation", solution="This plan is built specifically around the constraint, not despite it", sort_order=4),
    ],
    plateau_actions=[
        PlateauAction(trigger_condition="Pain not improving (2+ weeks)", action_to_take="Reduce range of motion further; consult a physiotherapist", timeframe="Immediate", sort_order=1),
        PlateauAction(trigger_condition="Strength plateau", action_to_take="Increase reps before increasing load", timeframe="Week 3-4", sort_order=2),
        PlateauAction(trigger_condition="No fat-loss results (4+ weeks)", action_to_take="Reassess calorie intake; pain shouldn't block nutrition progress", timeframe="Week 4", sort_order=3),
    ],
    faqs=[
        FAQ(question="Can I still build muscle with knee pain?", answer="Yes. Focus on pain-free range of motion, machine-supported movements, and upper body/core work.", sort_order=1),
        FAQ(question="Should I stop all leg exercises?", answer="No — complete avoidance weakens the muscles that support the knee. Modify, don't eliminate.", sort_order=2),
        FAQ(question="When should I see a doctor instead of following this plan?", answer="If pain is sharp, swelling appears, or pain worsens session over session, see a physiotherapist or doctor before continuing.", sort_order=3),
        FAQ(question="Is walking safe for knee pain?", answer="Generally yes, on flat surfaces, in supportive footwear. Stop if pain increases during the walk.", sort_order=4),
    ],
    tracker_columns=[
        TrackerColumn(column_name="Weight", sort_order=1),
        TrackerColumn(column_name="Pain Level (1-10)", sort_order=2),
        TrackerColumn(column_name="Mobility (1-10)", sort_order=3),
        TrackerColumn(column_name="Steps/Day", sort_order=4),
        TrackerColumn(column_name="Protein (g)", sort_order=5),
        TrackerColumn(column_name="Notes", sort_order=6),
    ],
)
