"""Busy Moms (Working Mothers) — original module from fitness_database.docx.

Auto-generated from /tmp/fitness_database.docx by scripts/import_docx.py.
Every row below traces to a row in the source DOCX. No content invented.
"""
from models.module import (
    Emotion,
    ExerciseAvoid,
    ExerciseRecommended,
    FAQ,
    FailedSolution,
    Food,
    FoodToAvoid,
    Habit,
    KeyMetric,
    MealIdea,
    ModuleConstraint,
    NutritionTarget,
    PlateauAction,
    PsychologyTechnique,
    PsychologyThought,
    RootCause,
    TrackerColumn,
    WorkoutExercise,
    WorkoutRoutine,
    Module,
)


MODULE = Module(
    slug="mom_strong",
    display_name="Busy Moms (Working Mothers)",
    audience="Working mothers aged 25-45 with children under 12",
    primary_goal="Fat loss + energy improvement + no guilt",
    main_barrier="No time; kids interrupting; guilt; perfectionism paralysis",
    pain_level=8,
    urgency=8,
    is_authored_extension=False,
    content_pending=False,
    emotions=[
    Emotion(emotion="Time Struggle", exact_phrase="Changing into workout gear", sort_order=1),
    Emotion(emotion="Confusion", exact_phrase="Not knowing what exercise to do", sort_order=2),
    Emotion(emotion="Time Struggle", exact_phrase="Not having a lot of time", sort_order=3),
    Emotion(emotion="Interruption", exact_phrase="Kids interrupting during session", sort_order=4),
    Emotion(emotion="Guilt", exact_phrase="guilt", sort_order=5),
    Emotion(emotion="Lack Support", exact_phrase="absence of support", sort_order=6),
    Emotion(emotion="Guilt", exact_phrase='Guilt about not being a "good mom" who prioritizes health', sort_order=7),
    Emotion(emotion="Shame", exact_phrase="shame comparing to fit moms", sort_order=8),
    Emotion(emotion="Exhaustion", exact_phrase="exhaustion from juggling", sort_order=9),
    Emotion(emotion="Fear", exact_phrase="fear of long-term health damage", sort_order=10),
    Emotion(emotion="Perfectionism", exact_phrase="perfectionism paralyzes them", sort_order=11),
],
    failed_solutions=[
    FailedSolution(solution_tried="60-minute gym classes", why_it_failed="Too long; kids wake up; no time available", sort_order=1),
    FailedSolution(solution_tried="Morning workouts", why_it_failed="Kids wake up; impossible to find quiet time", sort_order=2),
    FailedSolution(solution_tried="Post-work sessions", why_it_failed="Too tired after work + kids; burnout", sort_order=3),
    FailedSolution(solution_tried="YouTube random workouts", why_it_failed="No structure; not interrupt-friendly; confusing", sort_order=4),
    FailedSolution(solution_tried="Meal prep services", why_it_failed="Kids don't eat it; too expensive; not practical", sort_order=5),
    FailedSolution(solution_tried="Traditional fitness apps", why_it_failed="Assume 1+ hour free; not mom-life adjusted", sort_order=6),
    FailedSolution(solution_tried="Mom-coaches (random)", why_it_failed="Inconsistent quality; not tested for real mom life", sort_order=7),
],
    root_causes=[
    RootCause(category="Lifestyle", root_cause="Time constraints (work + kids + household)", sort_order=1),
    RootCause(category="Lifestyle", root_cause="Kids interrupting constantly", sort_order=2),
    RootCause(category="Lifestyle", root_cause="No support system (solo parenting often)", sort_order=3),
    RootCause(category="Lifestyle", root_cause="Gym equipment not accessible (home-only)", sort_order=4),
    RootCause(category="Lifestyle", root_cause="Exhaustion from juggling multiple roles", sort_order=5),
    RootCause(category="Lifestyle", root_cause="Sleep deprivation (kids wake up)", sort_order=6),
    RootCause(category="Psychological", root_cause='Guilt about not being a "good mom"', sort_order=7),
    RootCause(category="Psychological", root_cause="Shame comparing to fit moms", sort_order=8),
    RootCause(category="Psychological", root_cause="Perfectionism paralysis", sort_order=9),
    RootCause(category="Psychological", root_cause="Low self-confidence", sort_order=10),
    RootCause(category="Psychological", root_cause="Fear of long-term health damage", sort_order=11),
    RootCause(category="Biological", root_cause="Hormonal changes (postpartum, stress)", sort_order=12),
    RootCause(category="Biological", root_cause="High cortisol (chronic stress)", sort_order=13),
    RootCause(category="Biological", root_cause="Fatigue from poor sleep", sort_order=14),
],
    nutrition_targets=[
    NutritionTarget(field_name="Field", field_value="Details", sort_order=1),
    NutritionTarget(field_name="Protein Target", field_value="100-120g per day", sort_order=2),
    NutritionTarget(field_name="Fiber Target", field_value="25-35g per day", sort_order=3),
    NutritionTarget(field_name="Carb Strategy", field_value="Moderate, focus on complex carbs", sort_order=4),
    NutritionTarget(field_name="Fat Strategy", field_value="Moderate healthy fats", sort_order=5),
    NutritionTarget(field_name="Meal Timing", field_value="Quick meals; family-friendly (kids eat same)", sort_order=6),
    NutritionTarget(field_name="Prep Strategy", field_value="15-min meals; no elaborate prep needed", sort_order=7),
],
    foods=[
    Food(diet_type="vegetarian", food_type="Protein", options="Paneer, Greek yogurt, Tofu, Moong dal, Lentils, Chickpeas, Eggs", sort_order=1),
    Food(diet_type="vegetarian", food_type="Carbs", options="Quinoa, Brown rice, Sweet potato, Oats, Whole wheat", sort_order=2),
    Food(diet_type="vegetarian", food_type="Fats", options="Olive oil, Coconut, Almonds, Walnuts, Flax seeds", sort_order=3),
    Food(diet_type="vegetarian", food_type="Vegetables", options="Spinach, Broccoli, Cauliflower, Bell peppers, Zucchini", sort_order=4),
    Food(diet_type="vegetarian", food_type="Quick Meals", options="Roti + sabzi, Dal, Rice, Salad, Yogurt", sort_order=5),
    Food(diet_type="non_vegetarian", food_type="Protein", options="Eggs, Chicken (lean), Fish (salmon, sardines), Shrimp", sort_order=1),
    Food(diet_type="non_vegetarian", food_type="Carbs", options="Quinoa, Brown rice, Sweet potato, Whole wheat", sort_order=2),
    Food(diet_type="non_vegetarian", food_type="Fats", options="Olive oil, Avocado, Walnuts", sort_order=3),
    Food(diet_type="non_vegetarian", food_type="Vegetables", options="Same as vegetarian", sort_order=4),
    Food(diet_type="non_vegetarian", food_type="Quick Meals", options="Chicken stir-fry, Egg curry, Fish grilled", sort_order=5),
],
    foods_to_avoid=[
    FoodToAvoid(food_type="Processed sugar", why_avoid="Increases inflammation; energy crashes", sort_order=1),
    FoodToAvoid(food_type="Refined carbs", why_avoid="Blood sugar spikes; fatigue", sort_order=2),
    FoodToAvoid(food_type="Excessive caffeine", why_avoid="Increases cortisol; worsens fatigue", sort_order=3),
    FoodToAvoid(food_type="Alcohol", why_avoid="Increases inflammation; poor sleep", sort_order=4),
    FoodToAvoid(food_type="Elaborate meal prep", why_avoid="Too time-consuming; not practical for moms", sort_order=5),
],
    meal_ideas=[
    MealIdea(meal_time="Breakfast", diet_type="vegetarian", meal_option="Paneer bhurji + 2 rotis + Yogurt", sort_order=1),
    MealIdea(meal_time="Breakfast", diet_type="non_vegetarian", meal_option="Eggs + 2 rotis + Spinach", sort_order=2),
    MealIdea(meal_time="Lunch", diet_type="vegetarian", meal_option="Moong dal + Brown rice + Sabzi + Yogurt", sort_order=3),
    MealIdea(meal_time="Lunch", diet_type="non_vegetarian", meal_option="Chicken curry + Quinoa + Vegetables", sort_order=4),
    MealIdea(meal_time="Dinner", diet_type="vegetarian", meal_option="Tofu stir-fry + Roti + Dal", sort_order=5),
    MealIdea(meal_time="Dinner", diet_type="non_vegetarian", meal_option="Fish grilled + Sweet potato + Broccoli", sort_order=6),
    MealIdea(meal_time="Snacks", diet_type="vegetarian", meal_option="Greek yogurt + Berries, Almonds, Roasted chana", sort_order=7),
    MealIdea(meal_time="Snacks", diet_type="non_vegetarian", meal_option="Eggs + Vegetables, Protein smoothie", sort_order=8),
    MealIdea(meal_time="Kids-Friendly", diet_type="vegetarian", meal_option="Veg paratha + Yogurt, Fruit, Nuts", sort_order=9),
    MealIdea(meal_time="Kids-Friendly", diet_type="non_vegetarian", meal_option="Egg curry + Roti, Chicken nuggets", sort_order=10),
],
    exercises_recommended=[
    ExerciseRecommended(exercise_type="Walking", frequency="Daily", duration="20-30 min", benefits="Low stress, fits into mom life, done with kids", sort_order=1),
    ExerciseRecommended(exercise_type="Strength Training", frequency="3x/week", duration="15-20 min", benefits="Builds muscle, boosts metabolism; interrupt-friendly", sort_order=2),
    ExerciseRecommended(exercise_type="Yoga", frequency="2-3x/week", duration="15-20 min", benefits="Reduces cortisol, improves flexibility; kids can join", sort_order=3),
    ExerciseRecommended(exercise_type="Pilates", frequency="2x/week", duration="15 min", benefits="Core strength, low impact; home-friendly", sort_order=4),
    ExerciseRecommended(exercise_type="Bodyweight Circuits", frequency="3x/week", duration="15 min", benefits="No equipment; interrupt-friendly; effective", sort_order=5),
    ExerciseRecommended(exercise_type="Resistance Bands", frequency="2-3x/week", duration="15 min", benefits="Home-friendly; quiet; kids nearby", sort_order=6),
],
    exercises_avoid=[
    ExerciseAvoid(exercise_type="60-minute gym classes", why_avoid="Too long; no time; kids wake up", sort_order=1),
    ExerciseAvoid(exercise_type="HIIT workouts", why_avoid="Too exhausting; increases cortisol; not sustainable", sort_order=2),
    ExerciseAvoid(exercise_type="Early morning (6 AM)", why_avoid="Kids wake up; impossible to find quiet time", sort_order=3),
    ExerciseAvoid(exercise_type="Late evening (after 9 PM)", why_avoid="Too tired; kids still awake; burnout", sort_order=4),
    ExerciseAvoid(exercise_type="High-impact jumping", why_avoid="Kids hear noise;引起的 complaints; not quiet", sort_order=5),
    ExerciseAvoid(exercise_type="Complex equipment", why_avoid="No gym access; not home-friendly", sort_order=6),
],
    workout_routines=[
    WorkoutRoutine(
        time_minutes=15,
        location="any",
        routine_label="Routine A",
        exercises=[
            WorkoutExercise(exercise_name="Warm-up Walk", reps_or_time="2 min", rest="—", sort_order=1),
            WorkoutExercise(exercise_name="Body Squats", reps_or_time="10 reps", rest="10 sec", sort_order=2),
            WorkoutExercise(exercise_name="Push-ups (knees)", reps_or_time="8 reps", rest="10 sec", sort_order=3),
            WorkoutExercise(exercise_name="Glute Bridges", reps_or_time="12 reps", rest="10 sec", sort_order=4),
            WorkoutExercise(exercise_name="Plank", reps_or_time="20 sec", rest="10 sec", sort_order=5),
            WorkoutExercise(exercise_name="Standing Knee Raises", reps_or_time="10 reps", rest="10 sec", sort_order=6),
            WorkoutExercise(exercise_name="Cool-down Stretch", reps_or_time="2 min", rest="—", sort_order=7),
        ],
    ),
    WorkoutRoutine(
        time_minutes=30,
        location="any",
        routine_label="Routine C",
        exercises=[
            WorkoutExercise(exercise_name="Warm-up Walk", reps_or_time="5 min", rest="—", sort_order=1),
            WorkoutExercise(exercise_name="Squat to Press", reps_or_time="8 reps x 3 sets", rest="30 sec", sort_order=2),
            WorkoutExercise(exercise_name="Bent-over Rows", reps_or_time="10 reps x 3 sets", rest="30 sec", sort_order=3),
            WorkoutExercise(exercise_name="Lunges", reps_or_time="8 reps each x 2 sets", rest="30 sec", sort_order=4),
            WorkoutExercise(exercise_name="Push-ups", reps_or_time="8 reps x 3 sets", rest="30 sec", sort_order=5),
            WorkoutExercise(exercise_name="Plank", reps_or_time="30 sec x 2 sets", rest="20 sec", sort_order=6),
            WorkoutExercise(exercise_name="Cool-down Stretch", reps_or_time="5 min", rest="—", sort_order=7),
        ],
    ),
],
    constraints=[
    ModuleConstraint(constraint_name="Home Workout", solution="Use minimal equipment", approach="Body squats, Push-ups, Glute bridges, Plank, Resistance band work", sort_order=1),
    ModuleConstraint(constraint_name="Busy Schedule", solution="15-minute version", approach="Routine A = 15 min total; do after kids nap", sort_order=2),
    ModuleConstraint(constraint_name="Kids Interrupting", solution="Interrupt-friendly design", approach="Pause mid-exercise; kids can join; no complex sequences", sort_order=3),
    ModuleConstraint(constraint_name="No Time (10 min)", solution="Minimum viable workout", approach="3 min walk + 5 min body squats/push-ups + 2 min stretch", sort_order=4),
    ModuleConstraint(constraint_name="Fatigue Day", solution="Recovery mode", approach="10 min walk + 5 min yoga + stretching only", sort_order=5),
    ModuleConstraint(constraint_name="No Support", solution="Solo-friendly", approach="All home-based; no gym needed; kids can be nearby", sort_order=6),
    ModuleConstraint(constraint_name="Perfectionism", solution='"Something is better than nothing"', approach="15 min = still counts; don't need 60 min", sort_order=7),
    ModuleConstraint(constraint_name="Sleep Deprivation", solution="Low-intensity only", approach="Walking + yoga; no HIIT; rest priority", sort_order=8),
],
    habits=[
    Habit(habit_name="Habit", daily_target="Daily Target", how_to_track="How to Track", sort_order=1),
    Habit(habit_name="Sleep", daily_target="7-8 hours", how_to_track="Sleep app / journal", sort_order=2),
    Habit(habit_name="Water", daily_target="2-3 liters", how_to_track="Water bottle with marks", sort_order=3),
    Habit(habit_name="Step Goals", daily_target="6,000 steps", how_to_track="Step counter / phone", sort_order=4),
    Habit(habit_name="Stress Reduction", daily_target="10 min/day", how_to_track="Meditation app / breathing", sort_order=5),
    Habit(habit_name="Morning Routine", daily_target="10 min", how_to_track="Journal + stretch + water", sort_order=6),
    Habit(habit_name="Protein Intake", daily_target="100-120g", how_to_track="Food tracker app", sort_order=7),
    Habit(habit_name="Evening Walk", daily_target="15 min", how_to_track="After dinner walk", sort_order=8),
    Habit(habit_name="Screen Time", daily_target="Reduce before bed", how_to_track="No screens 1 hr before sleep", sort_order=9),
],
    psychology_thoughts=[
    PsychologyThought(common_thought="I'm not a good mom.", emotional_impact="Guilt", solution='Reframe: "Taking care of myself = better mom"', sort_order=1),
    PsychologyThought(common_thought="I always fail.", emotional_impact="Self-trust broken", solution="Habit stacking + micro-goals (15 min)", sort_order=2),
    PsychologyThought(common_thought="I'm broken.", emotional_impact="Feeling unfixable", solution="Education on mom-life + exercise connection", sort_order=3),
    PsychologyThought(common_thought="I have no discipline.", emotional_impact="Shame cycle", solution="Minimum viable workouts (15 min)", sort_order=4),
    PsychologyThought(common_thought="Everyone else succeeds.", emotional_impact="Comparison pain", solution="Focus on YOUR progress, not fit moms", sort_order=5),
    PsychologyThought(common_thought="I quit too easily.", emotional_impact="Self-blame", solution='Identity change: "I\'m someone who shows up consistently"', sort_order=6),
    PsychologyThought(common_thought="I don't have time.", emotional_impact="overwhelm", solution="Time-blocking + 15-min routines", sort_order=7),
    PsychologyThought(common_thought="Kids need me always.", emotional_impact="No freedom", solution="Interrupt-friendly design; kids can join", sort_order=8),
    PsychologyThought(common_thought="I'm too tired.", emotional_impact="Exhaustion", solution="Low-intensity only; rest is priority", sort_order=9),
],
    psychology_techniques=[
    PsychologyTechnique(technique="Habit Stacking", how_to_apply="Attach workout to existing habit (e.g., after kids nap)", sort_order=1),
    PsychologyTechnique(technique="Minimum Viable Workouts", how_to_apply="15-min routine = still counts as showing up", sort_order=2),
    PsychologyTechnique(technique="Identity Change", how_to_apply='Daily phrase: "I\'m a mom who respects my health"', sort_order=3),
    PsychologyTechnique(technique="Progress Tracking", how_to_apply="Track energy + mood, not just weight", sort_order=4),
    PsychologyTechnique(technique="Reframe Failure", how_to_apply='"Quitting" → "I\'m learning what works for MOM LIFE"', sort_order=5),
    PsychologyTechnique(technique="Perfectionism Kill", how_to_apply='"Something is better than nothing" message', sort_order=6),
],
    plateau_actions=[
    PlateauAction(trigger_condition="Weight pause (2+ weeks)", action_to_take="Increase protein by 10-15g", timeframe="Immediate", sort_order=1),
    PlateauAction(trigger_condition="Weight pause (2+ weeks)", action_to_take="Increase steps by 1,000/day", timeframe="Immediate", sort_order=2),
    PlateauAction(trigger_condition="Weight pause (2+ weeks)", action_to_take="Add 1 rest day/week (more recovery)", timeframe="Week 3-4", sort_order=3),
    PlateauAction(trigger_condition="Weight pause (2+ weeks)", action_to_take="Stress management (meditation 10 min/day)", timeframe="Daily", sort_order=4),
    PlateauAction(trigger_condition="Energy drops", action_to_take="Add 1-2 rest days/week", timeframe="Immediate", sort_order=5),
    PlateauAction(trigger_condition="Mood worsens", action_to_take="Reduce workout intensity; increase yoga", timeframe="Immediate", sort_order=6),
    PlateauAction(trigger_condition="No results (4+ weeks)", action_to_take="Reassess calorie intake (don't crash diet)", timeframe="Week 4", sort_order=7),
    PlateauAction(trigger_condition="No results (4+ weeks)", action_to_take="Check sleep quality + stress levels", timeframe="Week 4", sort_order=8),
    PlateauAction(trigger_condition="No results (4+ weeks)", action_to_take="Kids' schedule adjustment (more support)", timeframe="Week 4", sort_order=9),
],
    faqs=[
    FAQ(question="Why am I not losing weight?", answer="Mom life = chronic stress + poor sleep + time constraints. Standard advice doesn't work. Need interrupt-friendly, mom-life adjusted approach.", sort_order=1),
    FAQ(question="Can I eat rice?", answer="Yes, choose brown rice/quinoa. Limit to 1/2 cup per meal. Pair with protein + fiber. Family eats same.", sort_order=2),
    FAQ(question="Should I do cardio?", answer="Yes, but LOW-INTENSITY only (walking). Avoid HIIT (too exhausting; increases cortisol). Walk with kids.", sort_order=3),
    FAQ(question="Is fasting good for moms?", answer="Generally NO. Intermittent fasting can worsen energy. Focus on consistent meals with protein. Family meals = your meals.", sort_order=4),
    FAQ(question="How much protein do I need?", answer="100-120g per day for fat loss + muscle retention. Family meals can include your protein.", sort_order=5),
    FAQ(question="Will strength training make me bulky?", answer="No. Strength training builds lean muscle, boosts metabolism. 15-min sessions are effective.", sort_order=6),
    FAQ(question="Can I exercise if kids interrupt?", answer="YES. Interrupt-friendly design built in. Pause mid-exercise; kids can join. Nothing is wasted.", sort_order=7),
    FAQ(question="How often should I workout?", answer="3x 15-min strength training, daily walking (20 min), 2-3x yoga (15 min). Rest 3-4 days/week.", sort_order=8),
    FAQ(question="What if I'm too tired?", answer="Do 10-min walk + 5-min yoga. Rest is priority. Low-intensity only on fatigue days.", sort_order=9),
    FAQ(question="Is mom-life fitness fixable?", answer='Not "cured" but MANAGED. Work WITH mom life, not against it. Results come with consistency + interrupt-friendly approach.', sort_order=10),
    FAQ(question="How do I find time?", answer="15-min workouts after kids nap; morning before kids wake; evening walk with kids. No 60-min classes needed.", sort_order=11),
    FAQ(question="Do I need gym equipment?", answer="NO. All home-based; minimal equipment (resistance bands optional). Kids can be nearby.", sort_order=12),
],
    tracker_columns=[
    TrackerColumn(column_name="Weight", sort_order=1),
    TrackerColumn(column_name="Body Measurements", sort_order=2),
    TrackerColumn(column_name="Photos", sort_order=3),
    TrackerColumn(column_name="Energy Level (1-10)", sort_order=4),
    TrackerColumn(column_name="Mood (1-10)", sort_order=5),
    TrackerColumn(column_name="Steps/Day", sort_order=6),
    TrackerColumn(column_name="Protein (g)", sort_order=7),
    TrackerColumn(column_name="Kids Interrupted?", sort_order=8),
    TrackerColumn(column_name="Notes", sort_order=9),
],
    key_metrics=[
    KeyMetric(metric_name="Energy Level", target="7+ average", why_important="Indicates mom-life stress managing well", sort_order=1),
    KeyMetric(metric_name="Steps/Day", target="6,000 steps", why_important="Improves metabolism; walk with kids", sort_order=2),
    KeyMetric(metric_name="Protein (g)", target="100-120g", why_important="Supports muscle + fat loss", sort_order=3),
    KeyMetric(metric_name="Sleep Hours", target="7-8 hours", why_important="Critical for energy; mom survival", sort_order=4),
    KeyMetric(metric_name="Workout Consistency", target="3x/week (15 min)", why_important="Builds habit; manageable for mom life", sort_order=5),
    KeyMetric(metric_name="Kids Interruptions", target="0-2 per workout", why_important="Acceptable; interrupt-friendly design works", sort_order=6),
],
)
