"""PCOS — original module from fitness_database.docx.

Auto-generated from /tmp/fitness_database.docx by scripts/import_docx.py.
Every row below traces to a row in the source DOCX. No content invented.
"""
from models.module import (
    Emotion,
    ExerciseAvoid,
    ExerciseRecommended,
    FAQ,
    FailedSolution,
    Food,
    Habit,
    KeyMetric,
    MealIdea,
    ModuleConstraint,
    NutritionTarget,
    PlateauAction,
    PsychologyTechnique,
    PsychologyThought,
    RootCause,
    TrackerColumn,
    WorkoutExercise,
    WorkoutRoutine,
    Module,
)


MODULE = Module(
    slug="pcos",
    display_name="PCOS",
    audience="Women aged 20-40 with PCOS diagnosis",
    primary_goal="Fat loss + energy improvement",
    main_barrier="Exercise doesn't work for their body; exhaustion",
    pain_level=9,
    urgency=9,
    is_authored_extension=False,
    content_pending=False,
    emotions=[
    Emotion(emotion="Frustration", exact_phrase="Nothing works for my body.", sort_order=1),
    Emotion(emotion="Frustration", exact_phrase="Exercise doesn't work for my body.", sort_order=2),
    Emotion(emotion="Exhaustion", exact_phrase="I'm tired all the time.", sort_order=3),
    Emotion(emotion="Exhaustion", exact_phrase="time constraints, exhaustion", sort_order=4),
    Emotion(emotion="Shame", exact_phrase="People think I'm lazy.", sort_order=5),
    Emotion(emotion="Shame", exact_phrase="laziness, tiredness", sort_order=6),
    Emotion(emotion="Confusion", exact_phrase="Everyone says something different.", sort_order=7),
    Emotion(emotion="Anxiety", exact_phrase="depression and anxiety", sort_order=8),
    Emotion(emotion="Anxiety", exact_phrase="anxiety about long-term health", sort_order=9),
    Emotion(emotion="Guilt", exact_phrase="guilt about laziness", sort_order=10),
    Emotion(emotion="Shame", exact_phrase="shame that standard advice fails", sort_order=11),
    Emotion(emotion="Feeling Broken", exact_phrase="Feels broken/unfixable", sort_order=12),
],
    failed_solutions=[
    FailedSolution(solution_tried="HIIT workouts", why_it_failed="Too exhausting; makes them more tired", sort_order=1),
    FailedSolution(solution_tried="Crash diets", why_it_failed="Weight regained after short-term loss", sort_order=2),
    FailedSolution(solution_tried="Intermittent fasting", why_it_failed="Hormonal issues worsened", sort_order=3),
    FailedSolution(solution_tried="Generic fitness plans", why_it_failed="Not personalized for PCOS hormones", sort_order=4),
    FailedSolution(solution_tried="Calorie restriction", why_it_failed="Weight won't budge despite effort", sort_order=5),
    FailedSolution(solution_tried="Standard cardio", why_it_failed="Doesn't address insulin resistance", sort_order=6),
    FailedSolution(solution_tried="Random Instagram workouts", why_it_failed="No prog-specific programming", sort_order=7),
],
    root_causes=[
    RootCause(category="Biological", root_cause="Insulin resistance", sort_order=1),
    RootCause(category="Biological", root_cause="Hormonal imbalance (elevated testosterone)", sort_order=2),
    RootCause(category="Biological", root_cause="High cortisol", sort_order=3),
    RootCause(category="Biological", root_cause="Impaired thyroid hormone utilisation", sort_order=4),
    RootCause(category="Biological", root_cause="Metabolic adaptation", sort_order=5),
    RootCause(category="Lifestyle", root_cause="Stress (work + family)", sort_order=6),
    RootCause(category="Lifestyle", root_cause="Poor sleep quality", sort_order=7),
    RootCause(category="Lifestyle", root_cause="Sedentary work (desk jobs)", sort_order=8),
    RootCause(category="Lifestyle", root_cause="Time constraints (family duties)", sort_order=9),
    RootCause(category="Lifestyle", root_cause="Climate factors (not accounted for)", sort_order=10),
    RootCause(category="Psychological", root_cause="Anxiety", sort_order=11),
    RootCause(category="Psychological", root_cause="Low motivation", sort_order=12),
    RootCause(category="Psychological", root_cause="Depression", sort_order=13),
    RootCause(category="Psychological", root_cause="Low self-confidence", sort_order=14),
    RootCause(category="Psychological", root_cause="Perfectionism paralysis", sort_order=15),
],
    nutrition_targets=[
    NutritionTarget(field_name="Field", field_value="Details", sort_order=1),
    NutritionTarget(field_name="Protein Target", field_value="100-120g per day", sort_order=2),
    NutritionTarget(field_name="Fiber Target", field_value="25-35g per day", sort_order=3),
    NutritionTarget(field_name="Carb Strategy", field_value="Low-moderate, focus on complex carbs", sort_order=4),
    NutritionTarget(field_name="Fat Strategy", field_value="Moderate healthy fats", sort_order=5),
],
    foods=[
    Food(diet_type="vegetarian", food_type="Protein", options="Paneer, Greek yogurt, Tofu, Moong dal, Lentils, Chickpeas", sort_order=1),
    Food(diet_type="vegetarian", food_type="Carbs", options="Quinoa, Brown rice, Sweet potato, Oats", sort_order=2),
    Food(diet_type="vegetarian", food_type="Fats", options="Olive oil, Coconut, Almonds, Walnuts, Flax seeds", sort_order=3),
    Food(diet_type="vegetarian", food_type="Vegetables", options="Spinach, Broccoli, Cauliflower, Bell peppers", sort_order=4),
    Food(diet_type="non_vegetarian", food_type="Protein", options="Eggs, Chicken (lean), Fish (salmon, sardines)", sort_order=1),
    Food(diet_type="non_vegetarian", food_type="Carbs", options="Quinoa, Brown rice, Sweet potato", sort_order=2),
    Food(diet_type="non_vegetarian", food_type="Fats", options="Olive oil, Avocado, Walnuts", sort_order=3),
    Food(diet_type="non_vegetarian", food_type="Vegetables", options="Same as vegetarian", sort_order=4),
],
    meal_ideas=[
    MealIdea(meal_time="Breakfast", diet_type="vegetarian", meal_option="Paneer bhurji + 2 eggs + Moong dal chilla", sort_order=1),
    MealIdea(meal_time="Breakfast", diet_type="non_vegetarian", meal_option="Eggs + Spinach + Whole grain toast", sort_order=2),
    MealIdea(meal_time="Lunch", diet_type="vegetarian", meal_option="Moong dal + Brown rice + Sabzi + Greek yogurt", sort_order=3),
    MealIdea(meal_time="Lunch", diet_type="non_vegetarian", meal_option="Chicken curry + Quinoa + Vegetables", sort_order=4),
    MealIdea(meal_time="Dinner", diet_type="vegetarian", meal_option="Tofu stir-fry + Veg soup + Dal", sort_order=5),
    MealIdea(meal_time="Dinner", diet_type="non_vegetarian", meal_option="Fish grilled + Sweet potato + Broccoli", sort_order=6),
    MealIdea(meal_time="Snacks", diet_type="vegetarian", meal_option="Greek yogurt + Berries, Almonds, Roasted chana", sort_order=7),
    MealIdea(meal_time="Snacks", diet_type="non_vegetarian", meal_option="Eggs + Vegetables, Protein smoothie", sort_order=8),
],
    exercises_recommended=[
    ExerciseRecommended(exercise_type="Walking", frequency="Daily", duration="30-45 min", benefits="Low stress, improves insulin", sort_order=1),
    ExerciseRecommended(exercise_type="Strength Training", frequency="3-4x/week", duration="30-45 min", benefits="Builds muscle, boosts metabolism", sort_order=2),
    ExerciseRecommended(exercise_type="Yoga", frequency="2-3x/week", duration="20-30 min", benefits="Reduces cortisol, improves flexibility", sort_order=3),
    ExerciseRecommended(exercise_type="Pilates", frequency="2x/week", duration="30 min", benefits="Core strength, low impact", sort_order=4),
    ExerciseRecommended(exercise_type="HIIT (Modified)", frequency="1x/week max", duration="15-20 min", benefits="Only if energy is high", sort_order=5),
    ExerciseRecommended(exercise_type="Resistance Bands", frequency="2-3x/week", duration="20 min", benefits="Home-friendly, low stress", sort_order=6),
],
    exercises_avoid=[
    ExerciseAvoid(exercise_type="Excessive HIIT", why_avoid="Increases cortisol, worsens PCOS", sort_order=1),
    ExerciseAvoid(exercise_type="Daily intense cardio", why_avoid="Too exhausting, burns out", sort_order=2),
    ExerciseAvoid(exercise_type="Long endurance sessions", why_avoid="(>60 min) Increases stress hormones", sort_order=3),
    ExerciseAvoid(exercise_type="Overtraining", why_avoid="Disrupts hormonal balance", sort_order=4),
    ExerciseAvoid(exercise_type="High-impact daily", why_avoid="Causes joint pain, fatigue", sort_order=5),
],
    workout_routines=[
    WorkoutRoutine(
        time_minutes=15,
        location="any",
        routine_label="Routine A",
        exercises=[
            WorkoutExercise(exercise_name="Warm-up Walk", reps_or_time="2 min", rest="—", sort_order=1),
            WorkoutExercise(exercise_name="Body Squats", reps_or_time="10 reps", rest="10 sec", sort_order=2),
            WorkoutExercise(exercise_name="Push-ups (knees)", reps_or_time="8 reps", rest="10 sec", sort_order=3),
            WorkoutExercise(exercise_name="Glute Bridges", reps_or_time="12 reps", rest="10 sec", sort_order=4),
            WorkoutExercise(exercise_name="Plank", reps_or_time="20 sec", rest="10 sec", sort_order=5),
            WorkoutExercise(exercise_name="Standing Knee Raises", reps_or_time="10 reps", rest="10 sec", sort_order=6),
            WorkoutExercise(exercise_name="Cool-down Stretch", reps_or_time="2 min", rest="—", sort_order=7),
        ],
    ),
    WorkoutRoutine(
        time_minutes=30,
        location="any",
        routine_label="Routine B",
        exercises=[
            WorkoutExercise(exercise_name="Warm-up Walk", reps_or_time="3 min", rest="—", sort_order=1),
            WorkoutExercise(exercise_name="Goblet Squats", reps_or_time="12 reps x 3 sets", rest="30 sec", sort_order=2),
            WorkoutExercise(exercise_name="Dumbbell Rows", reps_or_time="10 reps x 3 sets", rest="30 sec", sort_order=3),
            WorkoutExercise(exercise_name="Romanian Deadlifts", reps_or_time="10 reps x 3 sets", rest="30 sec", sort_order=4),
            WorkoutExercise(exercise_name="Overhead Press", reps_or_time="8 reps x 3 sets", rest="30 sec", sort_order=5),
            WorkoutExercise(exercise_name="Bird Dogs", reps_or_time="10 reps x 2 sets", rest="20 sec", sort_order=6),
            WorkoutExercise(exercise_name="Cool-down Yoga", reps_or_time="5 min", rest="—", sort_order=7),
        ],
    ),
    WorkoutRoutine(
        time_minutes=45,
        location="any",
        routine_label="Routine C",
        exercises=[
            WorkoutExercise(exercise_name="Warm-up Walk", reps_or_time="5 min", rest="—", sort_order=1),
            WorkoutExercise(exercise_name="Squat to Press", reps_or_time="10 reps x 4 sets", rest="30 sec", sort_order=2),
            WorkoutExercise(exercise_name="Bent-over Rows", reps_or_time="12 reps x 4 sets", rest="30 sec", sort_order=3),
            WorkoutExercise(exercise_name="Lunges", reps_or_time="10 reps each x 3 sets", rest="30 sec", sort_order=4),
            WorkoutExercise(exercise_name="Push-ups", reps_or_time="8-10 reps x 3 sets", rest="30 sec", sort_order=5),
            WorkoutExercise(exercise_name="Wall Sit", reps_or_time="30 sec x 3 sets", rest="20 sec", sort_order=6),
            WorkoutExercise(exercise_name="Light Jog/Walk", reps_or_time="5 min", rest="—", sort_order=7),
            WorkoutExercise(exercise_name="Cool-down Stretch", reps_or_time="5 min", rest="—", sort_order=8),
        ],
    ),
],
    constraints=[
    ModuleConstraint(constraint_name="Home Workout", solution="Use minimal equipment", approach="Body squats, Push-ups, Glute bridges, Plank, Resistance band work", sort_order=1),
    ModuleConstraint(constraint_name="Gym Workout", solution="Full equipment access", approach="Goblet squats, Dumbbell rows, RDLs, Overhead press, Cable work", sort_order=2),
    ModuleConstraint(constraint_name="Busy Schedule", solution="20-minute version", approach="Routine A + 5 min walk = 20 min total", sort_order=3),
    ModuleConstraint(constraint_name="Knee Pain", solution="Low-impact alternatives", approach="Replace squats with leg press, replace lunges with seated leg extensions", sort_order=4),
    ModuleConstraint(constraint_name="No Time (10 min)", solution="Minimum viable workout", approach="3 min walk + 5 min body squats/push-ups + 2 min stretch", sort_order=5),
    ModuleConstraint(constraint_name="Fatigue Day", solution="Recovery mode", approach="15 min walk + 5 min yoga + stretching only", sort_order=6),
    ModuleConstraint(constraint_name="Pain Day", solution="Gentle movement", approach="Walking only, no strength training", sort_order=7),
    ModuleConstraint(constraint_name="Incontinence", solution="Avoid high-impact", approach="Skip jumping, focus on strength + walking", sort_order=8),
],
    habits=[
    Habit(habit_name="Sleep", daily_target="7-8 hours", how_to_track="Sleep app / journal", sort_order=1),
    Habit(habit_name="Water", daily_target="2-3 liters", how_to_track="Water bottle with marks", sort_order=2),
    Habit(habit_name="Step Goals", daily_target="6,000-8,000 steps", how_to_track="Step counter / phone", sort_order=3),
    Habit(habit_name="Stress Reduction", daily_target="10 min/day", how_to_track="Meditation app / breathing", sort_order=4),
    Habit(habit_name="Morning Routine", daily_target="15 min", how_to_track="Journal + stretch + water", sort_order=5),
    Habit(habit_name="Protein Intake", daily_target="100-120g", how_to_track="Food tracker app", sort_order=6),
    Habit(habit_name="Evening Walk", daily_target="15-20 min", how_to_track="After dinner walk", sort_order=7),
    Habit(habit_name="Screen Time", daily_target="Reduce before bed", how_to_track="No screens 1 hr before sleep", sort_order=8),
],
    psychology_thoughts=[
    PsychologyThought(common_thought="I always fail.", emotional_impact="Self-trust broken", solution="Habit stacking + micro-goals", sort_order=1),
    PsychologyThought(common_thought="I'm broken.", emotional_impact="Feeling unfixable", solution="Education on PCOS + exercise connection", sort_order=2),
    PsychologyThought(common_thought="I have no discipline.", emotional_impact="Shame cycle", solution="Minimum viable workouts (15 min)", sort_order=3),
    PsychologyThought(common_thought="I'm lazy.", emotional_impact="Guilt", solution="Reframe: My body needs different approach", sort_order=4),
    PsychologyThought(common_thought="This won't work for me.", emotional_impact="Hopelessness", solution="Start with 1-week trial, track energy", sort_order=5),
    PsychologyThought(common_thought="Everyone else succeeds.", emotional_impact="Comparison pain", solution="Focus on YOUR progress, not others", sort_order=6),
    PsychologyThought(common_thought="I quit too easily.", emotional_impact="Self-blame", solution="Identity change: I'm someone who shows up consistently", sort_order=7),
    PsychologyThought(common_thought="I don't have time.", emotional_impact="overwhelm", solution="Time-blocking + 15-min routines", sort_order=8),
],
    psychology_techniques=[
    PsychologyTechnique(technique="Habit Stacking", how_to_apply="Attach workout to existing habit (e.g., after coffee)", sort_order=1),
    PsychologyTechnique(technique="Minimum Viable Workouts", how_to_apply="15-min routine = still counts as showing up", sort_order=2),
    PsychologyTechnique(technique="Identity Change", how_to_apply="Daily phrase: I'm someone who respects my body", sort_order=3),
    PsychologyTechnique(technique="Progress Tracking", how_to_apply="Track energy + mood, not just weight", sort_order=4),
    PsychologyTechnique(technique="Reframe Failure", how_to_apply="Quitting → I'm learning what works for MY body", sort_order=5),
],
    plateau_actions=[
    PlateauAction(trigger_condition="Weight pause (2+ weeks)", action_to_take="Increase protein by 10-15g", timeframe="Immediate", sort_order=1),
    PlateauAction(trigger_condition="Weight pause (2+ weeks)", action_to_take="Increase steps by 1,000/day", timeframe="Immediate", sort_order=2),
    PlateauAction(trigger_condition="Weight pause (2+ weeks)", action_to_take="Add 1 deload week (reduce intensity)", timeframe="Week 3-4", sort_order=3),
    PlateauAction(trigger_condition="Weight pause (2+ weeks)", action_to_take="Stress management (meditation 10 min/day)", timeframe="Daily", sort_order=4),
    PlateauAction(trigger_condition="Energy drops", action_to_take="Add 1 rest day/week", timeframe="Immediate", sort_order=5),
    PlateauAction(trigger_condition="Mood worsens", action_to_take="Reduce cardio, increase strength", timeframe="Immediate", sort_order=6),
    PlateauAction(trigger_condition="No results (4+ weeks)", action_to_take="Reassess calorie intake + protein", timeframe="Week 4", sort_order=7),
    PlateauAction(trigger_condition="No results (4+ weeks)", action_to_take="Check sleep quality + stress levels", timeframe="Week 4", sort_order=8),
],
    faqs=[
    FAQ(question="Why am I not losing weight?", answer="PCOS causes insulin resistance + hormonal imbalance. Standard advice doesn't work. Need hormone-synced approach.", sort_order=1),
    FAQ(question="Can I eat rice?", answer="Yes, but choose brown rice/quinoa. Limit to 1/2 cup per meal. Pair with protein + fiber.", sort_order=2),
    FAQ(question="Should I do cardio?", answer="Yes, but LOW-INTENSITY (walking). Avoid excessive HIIT/intense cardio (increases cortisol).", sort_order=3),
    FAQ(question="Is fasting good for PCOS?", answer="Generally NO. Intermittent fasting can worsen hormonal issues. Focus on consistent meals with protein.", sort_order=4),
    FAQ(question="How much protein do I need?", answer="100-120g per day for fat loss + muscle retention.", sort_order=5),
    FAQ(question="Will strength training make me bulky?", answer="No. Strength training builds lean muscle, boosts metabolism, improves insulin sensitivity.", sort_order=6),
    FAQ(question="Can I exercise if I'm exhausted?", answer="Yes, but modify. Do 15-min walk + light yoga instead of intense workout.", sort_order=7),
    FAQ(question="How often should I workout?", answer="3-4x strength training, daily walking, 2-3x yoga. Rest 2-3 days/week.", sort_order=8),
    FAQ(question="What if I have knee pain?", answer="Avoid jumping/high-impact. Use leg press instead of squats, seated exercises.", sort_order=9),
    FAQ(question="Is PCOS fixable?", answer="Not cured but MANAGED. Work WITH hormones, not against them. Results come with consistency.", sort_order=10),
],
    tracker_columns=[
    TrackerColumn(column_name="Weight", sort_order=1),
    TrackerColumn(column_name="Body Measurements", sort_order=2),
    TrackerColumn(column_name="Photos", sort_order=3),
    TrackerColumn(column_name="Energy Level (1-10)", sort_order=4),
    TrackerColumn(column_name="Mood (1-10)", sort_order=5),
    TrackerColumn(column_name="Steps/Day", sort_order=6),
    TrackerColumn(column_name="Protein (g)", sort_order=7),
    TrackerColumn(column_name="Notes", sort_order=8),
],
    key_metrics=[
    KeyMetric(metric_name="Energy Level", target="7+ average", why_important="Indicates hormonal balance improving", sort_order=1),
    KeyMetric(metric_name="Steps/Day", target="6,000-8,000", why_important="Improves insulin sensitivity", sort_order=2),
    KeyMetric(metric_name="Protein (g)", target="100-120g", why_important="Supports muscle + fat loss", sort_order=3),
    KeyMetric(metric_name="Sleep Hours", target="7-8 hours", why_important="Reduces cortisol", sort_order=4),
    KeyMetric(metric_name="Workout Consistency", target="3-4x/week", why_important="Builds habit + results", sort_order=5),
],
)
